### ISSUE TITLE
Freeswitch leaves stale calls

### ISSUE THREAD

**Issue by greenbea** [signalwire/freeswitch#2372] opened 2024-01-26 05:11 UTC
**Describe the bug**
Freeswitch leaves a lot of stale calls in memory and in db. In the past, we experienced this seldomly, and it was only stale calls in the database, but not in memory. However, the same day we started to use the latest freeswitch version 1.10.11, we saw a lot of stale calls, and `uuid_exists` returned true on those calls, indicating the calls were still in memory. So this is more of a serious bug.

I've seen this very same issue reported on the slack channel, that after an update to the latest freeswitch there's an increase in stale calls.

**Package version or git hash**
 - Version 1.10.11

**Comment by greenbea** [comment] 2024-01-26 06:18
I took a [core dump](https://github.com/signalwire/freeswitch/files/14060914/gdb.txt) and found deadlocks causing stale calls. The gdb output is just from 1 call, but all the others look very alike.

The gdb output is from the following commands.
```
thread 78
bt
frame 3
p *mutex
thread 79
bt
frame 3
p *mutex
```

**Comment by greenbea** [comment] 2024-01-26 06:48
It appears this is the same issue as https://github.com/signalwire/freeswitch/issues/2290

**Comment by technophreak** [comment] 2024-02-02 14:52
I have the same issue with 1.10.11, I will try with 1.10.10 and report back with findings.

**Comment by wesmu** [comment] 2024-02-02 15:19
Hi everyone,
Is this issue linked to audio transcoding? We don't have any transcoding in our side so I would like to know it before upgrading to the latest version.
Thanks in advance.
Best Regards

**Comment by bferreirq** [comment] 2024-02-05 14:35
Hello, which OS version in your case ?
Since we upgraded to Debian 12 with FreeSWITCH in v1.10.11 we have same issue.
A lot of call not hung up by FS.

After checking in detail a lot of packets (200OK, BYE) seem to be randomly ignored by FS.

Same issue for you ?

![image](https://github.com/signalwire/freeswitch/assets/41393644/8ca335fc-dea9-4f29-8557-b3b415b0bf17)

Regards,

**Comment by wesmu** [comment] 2024-02-05 16:45
> Hello, which OS version in your case ? Since we upgraded to Debian 12 with FreeSWITCH in v1.10.11 we have same issue. A lot of call not hung up by FS.
> 
> After checking in detail a lot of packets (200OK, BYE) seem to be randomly ignored by FS. So after few days we have a lot of "ghost" call in memory of fs_cli
> 
> Same issue for you ?
> 
> ![image](https://private-user-images.githubusercontent.com/41393644/302323758-8ca335fc-dea9-4f29-8557-b3b415b0bf17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNTE3MDEsIm5iZiI6MTcwNzE1MTQwMSwicGF0aCI6Ii80MTM5MzY0NC8zMDIzMjM3NTgtOGNhMzM1ZmMtZGVhOS00ZjI5LTg1NTctYjNiNDE1YjBiZjE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDE2NDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMTBlMjM3NDY1MGVlMWEzZGMyYTlkNGY5NzA0NWJhNGI0OTY2NDg2NTYwYThhNDU0MWI4YWY1ODhhOTFiNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i-ZrtgD1HJnEIt7d56dSyURPkWEJlzhFFSNMwIzpmoQ)
> 
> Regards,

Take a look on CONTACT header sent in the INVITE, it seems the other end is sending all the answers to one address is not where the FS is listening on (assuming FS sent the second INVITE...)

**Comment by bferreirq** [comment] 2024-02-05 16:55
Yes, everything is good on contact side, it's totally random over several thousand calls per day

**Comment by technophreak** [comment] 2024-02-05 18:06
I am using Debian 12. I have not noticed any issue with 200 OK. I will take a closer look and report if I find anything on that regard.

**Comment by greenbea** [comment] 2024-02-05 18:23
> Hi everyone, Is this issue linked to audio transcoding? We don't have any transcoding in our side so I would like to know it before upgrading to the latest version. Thanks in advance. Best Regards

The issue isn't related to transcoding. See issue https://github.com/signalwire/freeswitch/issues/2290 for the details of this deadlock.

**Comment by bferreirq** [comment] 2024-02-05 18:23
@technophreak 
I tried to reproduce in different ways with a SIPp in all directions and I not reproduce.

But randomly it happens and after few days we have like 100 fake active calls on freeswitch (fs_cli -x show calls) due to this problem (when we check 200OK, BYE is ignored)

Of course, Contact, Via and other fields seems good.

For me happening after upgrade to Deb12 and 1.10.10.
I’ve upgrade to 1.10.11 in order to test but its not better.

If i can help tell me, thanks a lot.

**Comment by technophreak** [comment] 2024-02-05 21:38
@bferreirq Yeah, in my case those stale calls are not even properly killed with uuid_kill, there are remnants. I suspect it is not directly related, perhaps your OK issue is just a symptom for the same issue.

**Comment by greenbea** [comment] 2024-02-05 21:40
You cannot kill those calls because they're mutex locked. The only way to get rid of them is to restart freeswitch.

**Comment by bferreirq** [comment] 2024-02-05 21:42
@technophreak Yes we schedule restarts to kill these calls.

**Comment by technophreak** [comment] 2024-02-05 21:51
@bferreirq The issue I have is that those have remants (still appears in `show calls`) after they get killed and I only restart when there are no more calls in progress.

Although rare, we do have very long calls, so I can't just assume that a 3 hour call is a ghost call and I have no indication if this call is still really legitimately connected.

This is a very annoying issue.

**Comment by technophreak** [comment] 2024-02-05 21:52
@greenbea Thanks for that info.

Have you found a way to know (via uuid_dump for example) if they are still really connected ?

**Comment by technophreak** [comment] 2024-02-13 19:38
In my specific scenario, the issue only occurred when transcoding inbound calls. It does not mean it only affects inbound calls, it's just that with my current configuration only inbound is being affected.

I've completed my tests and I can confirm for sure that v1.10.8 and v1.10.9 does not have this issue.

I will go ahead and test version 1.10.10 now and report back.

**Comment by bferreirq** [comment] 2024-02-14 09:52
> In my specific scenario, the issue only occurred when transcoding inbound calls. It does not mean it only affects inbound calls, it's just that with my current configuration only inbound is being affected.
> 
> I've completed my tests and I can confirm for sure that v1.10.8 and v1.10.9 does not have this issue.
> 
> I will go ahead and test version 1.10.10 now and report back.

could you please share your sip scenario ?

**Comment by technophreak** [comment] 2024-02-15 18:47
@bferreirq The calls that seems to trigger most often this issue are as follow:
* [A LEG] Call comes in sip_profile (operator) with G729,PCMU as codec offered
 Porifile set to greedy, disable transcoding on, late-negotiation on
 * [B LEG] Call is bridged to user in sip_profile (customer) with PCMU as codec accepted
  Profile set to greedy, disable transcoding off, late nego on
 
 --
 
 I have however seen many calls that are PCMU all the way get stuck as well.

**Comment by technophreak** [comment] 2024-02-15 18:50
I can confirm I am also getting stale/stuck calls with v1.10.10

As far as I am concenred, here is my diagnostic:
* v1.10.8 : Not affected
* v1.10.9 : Not affected
* v1.10.10 : Affected
* v1.10.11 : Affected

--

To add insult to the injury. I cannot even use v1.10.9 because it seems to have issues with `rxfax` for one of my carrier.

**Comment by phamhieptel4vn** [comment] 2024-04-04 05:27
> I can confirm I am also getting stale/stuck calls with v1.10.10
> 
> As far as I am concenred, here is my diagnostic:
> 
> * v1.10.8 : Not affected
> * v1.10.9 : Not affected
> * v1.10.10 : Affected
> * v1.10.11 : Affected
> 
> --
> 
> To add insult to the injury. I cannot even use v1.10.9 because it seems to have issues with `rxfax` for one of my carrier.

I have the same problem in 1.10.10-release. Although the actual call has ended, the channel inside Freeswitch has not been hung up, so the CDR has not been updated.
![image](https://github.com/signalwire/freeswitch/assets/83744201/4e3caaef-6255-4d74-8599-087fd4f611c0)

**Comment by shaunjstokes** [comment] 2024-04-04 06:16
We had the same issue, you should check the following patch.
https://github.com/signalwire/freeswitch/pull/2300

**Comment by phamhieptel4vn** [comment] 2024-04-04 06:37
> We had the same issue, you should check the following patch. #2300

Could you tell me if this PR has resolved the issue?

**Comment by jakubkarolczyk** [comment] 2024-10-10 23:22
Fixed in https://github.com/signalwire/freeswitch/pull/2619

**Closed by jakubkarolczyk** 2024-10-10 23:22 UTC
Labels: bug

**Comment by rlaager** [comment] 2025-01-30 04:40
> > We had the same issue, you should check the following patch. [#2300](https://github.com/signalwire/freeswitch/pull/2300)
> 
> Could you tell me if this PR has resolved the issue?

We (Wikstrom Telephone Company) had stale/stuck calls regularly. We believe that commit b4ebd0936c756f32a5e65ec181429a431dff4505 / PR #2619 fixes the issue. (PR #2300 also fixed it for us.)
