### ISSUE TITLE
freeSWITCH 1.8.7 Program terminated with signal 6

### ISSUE THREAD

**Issue by yaoshenshen** [signalwire/freeswitch#1038] opened 2021-01-22 06:38 UTC
**Describe the bug**
freeSWITCH 1.8.7
OS：CentOS Linux release 7.4.1708 (Core) 
kernal：Linux localhost.localdomain 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

ldns version：
ldns-1.6.16-10.el7.x86_64
ldns-devel-1.6.16-10.el7.x86_64

run command "freeswitch -nc" at centos7.4 ,after few min The fressswitch process is missing and create core.5587

run command “gdb freeswitch core.5587”
[New LWP 7183]
[New LWP 5850]
[New LWP 6022]
[New LWP 7231]
[New LWP 6216]
[New LWP 5802]
[New LWP 6290]
[New LWP 5777]
[New LWP 7244]
[New LWP 6168]
[New LWP 6115]
[New LWP 5624]
[New LWP 7303]
[New LWP 6435]
[New LWP 6084]
[New LWP 6031]
[New LWP 7126]
[New LWP 6463]
[New LWP 7060]
[New LWP 5841]
[New LWP 7064]
[New LWP 5998]
[New LWP 5608]
[New LWP 6082]
[New LWP 6340]
[New LWP 7410]
[New LWP 5755]
[New LWP 7318]
[New LWP 6100]
[New LWP 6147]
[New LWP 6495]
[New LWP 6243]
[New LWP 5703]
[New LWP 6370]
[New LWP 7063]
[New LWP 7321]
[New LWP 5844]
[New LWP 5636]
[New LWP 6055]
[New LWP 6151]
[New LWP 6378]
[New LWP 5622]
[New LWP 6394]
[New LWP 6334]
[New LWP 7358]
[New LWP 6106]
[New LWP 5719]
[New LWP 5678]
[New LWP 6220]
[New LWP 5910]
[New LWP 6269]
[New LWP 6979]
[New LWP 6436]
[New LWP 7147]
[New LWP 7090]
[New LWP 5643]
[New LWP 6283]
[New LWP 5951]
[New LWP 6034]
[New LWP 6098]
[New LWP 5870]
[New LWP 5832]
[New LWP 5736]
[New LWP 5706]
[New LWP 6331]
[New LWP 6105]
[New LWP 6046]
[New LWP 6140]
[New LWP 7412]
[New LWP 6561]
[New LWP 5764]
[New LWP 6456]
[New LWP 6163]
[New LWP 7245]
[New LWP 5896]
[New LWP 7018]
[New LWP 5721]
[New LWP 6288]
[New LWP 5663]
[New LWP 6488]
[New LWP 5987]
[New LWP 6087]
[New LWP 5894]
[New LWP 6059]
[New LWP 5825]
[New LWP 6303]
[New LWP 5748]
[New LWP 5707]
[New LWP 6357]
[New LWP 6126]
[New LWP 6058]
[New LWP 7181]
[New LWP 5796]
[New LWP 6162]
[New LWP 6019]
[New LWP 7341]
[New LWP 6287]
[New LWP 7390]
[New LWP 7289]
[New LWP 6294]
[New LWP 6206]
[New LWP 5665]
[New LWP 5964]
[New LWP 5935]
[New LWP 6073]
[New LWP 5890]
[New LWP 6051]
[New LWP 5835]
[New LWP 6250]
[New LWP 6050]
[New LWP 5749]
[New LWP 6364]
[New LWP 6128]
[New LWP 5722]
[New LWP 5761]
[New LWP 6219]
[New LWP 7029]
[New LWP 6015]
[New LWP 6003]
[New LWP 7347]
[New LWP 7300]
[New LWP 6307]
[New LWP 6156]
[New LWP 5980]
[New LWP 5668]
[New LWP 5776]
[New LWP 6039]
[New LWP 6119]
[New LWP 5920]
[New LWP 5836]
[New LWP 6403]
[New LWP 5885]
[New LWP 5713]
[New LWP 5879]
[New LWP 6365]
[New LWP 6145]
[New LWP 7374]
[New LWP 5752]
[New LWP 6254]
[New LWP 5726]
[New LWP 5848]
[New LWP 7197]
[New LWP 6360]
[New LWP 7099]
[New LWP 6125]
[New LWP 5950]
[New LWP 5695]
[New LWP 6408]
[New LWP 6060]
[New LWP 6124]
[New LWP 5887]
[New LWP 5838]
[New LWP 6472]
[New LWP 5903]
[New LWP 5702]
[New LWP 6350]
[New LWP 6158]
[New LWP 7221]
[New LWP 5793]
[New LWP 6203]
[New LWP 5914]
[New LWP 7106]
[New LWP 5788]
[New LWP 5662]
[New LWP 6330]
[New LWP 6182]
[New LWP 7409]
[New LWP 5949]
[New LWP 5698]
[New LWP 6063]
[New LWP 6048]
[New LWP 5911]
[New LWP 5849]
[New LWP 6246]
[New LWP 6007]
[New LWP 5709]
[New LWP 6157]
[New LWP 7295]
[New LWP 6249]
[New LWP 5818]
[New LWP 6090]
[New LWP 5674]
[New LWP 6426]
[New LWP 7214]
[New LWP 6428]
[New LWP 6094]
[New LWP 7022]
[New LWP 6009]
[New LWP 6036]
[New LWP 5857]
[New LWP 5701]
[New LWP 7065]
[New LWP 6056]
[New LWP 6238]
[New LWP 5728]
[New LWP 7105]
[New LWP 6127]
[New LWP 5772]
[New LWP 7091]
[New LWP 6281]
[New LWP 7340]
[New LWP 5847]
[New LWP 6368]
[New LWP 6107]
[New LWP 7333]
[New LWP 6152]
[New LWP 5918]
[New LWP 7217]
[New LWP 5700]
[New LWP 5977]
[New LWP 6208]
[New LWP 5735]
[New LWP 7172]
[New LWP 5895]
[New LWP 5770]
[New LWP 6940]
[New LWP 5754]
[New LWP 6245]
[New LWP 7247]
[New LWP 7283]
[New LWP 6257]
[New LWP 6450]
[New LWP 6067]
[New LWP 7329]
[New LWP 6332]
[New LWP 5621]
[New LWP 5773]
[New LWP 6251]
[New LWP 5724]
[New LWP 6814]
[New LWP 7396]
[New LWP 5760]
[New LWP 5781]
[New LWP 6869]
[New LWP 7182]
[New LWP 6227]
[New LWP 7045]
[New LWP 6984]
[New LWP 5830]
[New LWP 6314]
[New LWP 6484]
[New LWP 6101]
[New LWP 7301]
[New LWP 5810]
[New LWP 5682]
[New LWP 5970]
[New LWP 6235]
[New LWP 6810]
[New LWP 6150]
[New LWP 6887]
[New LWP 5765]
[New LWP 5644]
[New LWP 7145]
[New LWP 6236]
[New LWP 7242]
[New LWP 7149]
[New LWP 6244]
[New LWP 6407]
[New LWP 6388]
[New LWP 7343]
[New LWP 5881]
[New LWP 5659]
[New LWP 5875]
[New LWP 6377]
[New LWP 6693]
[New LWP 6170]
[New LWP 6842]
[New LWP 5821]
[New LWP 7261]
[New LWP 7082]
[New LWP 6213]
[New LWP 7337]
[New LWP 6620]
[New LWP 6204]
[New LWP 6386]
[New LWP 6248]
[New LWP 7310]
[New LWP 5725]
[New LWP 5681]
[New LWP 6483]
[New LWP 6422]
[New LWP 5973]
[New LWP 6774]
[New LWP 6032]
[New LWP 6849]
[New LWP 5767]
[New LWP 7428]
[New LWP 7342]
[New LWP 7135]
[New LWP 6293]
[New LWP 6641]
[New LWP 6309]
[New LWP 7323]
[New LWP 7239]
[New LWP 6354]
[New LWP 5968]
[New LWP 7407]
[New LWP 6342]
[New LWP 6218]
[New LWP 6711]
[New LWP 6927]
[New LWP 6190]
[New LWP 5699]
[New LWP 7103]
[New LWP 7416]
[New LWP 7215]
[New LWP 6011]
[New LWP 7108]
[New LWP 7279]
[New LWP 6568]
[New LWP 6375]
[New LWP 5876]
[New LWP 7437]
[New LWP 6326]
[New LWP 6660]
[New LWP 6452]
[New LWP 6873]
[New LWP 6043]
[New LWP 5858]
[New LWP 5654]
[New LWP 7331]
[New LWP 7355]
[New LWP 7229]
[New LWP 5945]
[New LWP 7125]
[New LWP 7292]
[New LWP 6502]
[New LWP 5750]
[New LWP 7413]
[New LWP 7166]
[New LWP 6738]
[New LWP 6454]
[New LWP 6273]
[New LWP 6867]
[New LWP 5780]
[New LWP 5753]
[New LWP 6187]
[New LWP 7391]
[New LWP 7040]
[New LWP 6016]
[New LWP 7127]
[New LWP 7364]
[New LWP 6482]
[New LWP 5834]
[New LWP 6792]
[New LWP 7165]
[New LWP 7419]
[New LWP 5686]
[New LWP 6296]
[New LWP 6969]
[New LWP 6141]
[New LWP 7043]
[New LWP 6228]
[New LWP 7233]
[New LWP 7042]
[New LWP 5994]
[New LWP 7012]
[New LWP 7360]
[New LWP 6229]
[New LWP 5738]
[New LWP 7439]
[New LWP 5693]
[New LWP 6970]
[New LWP 5939]
[New LWP 6268]
[New LWP 5605]
[New LWP 6062]
[New LWP 5649]
[New LWP 7077]
[New LWP 7257]
[New LWP 6252]
[New LWP 7405]
[New LWP 5639]
[New LWP 5680]
[New LWP 6108]
[New LWP 6956]
[New LWP 7286]
[New LWP 7168]
[New LWP 6345]
[New LWP 5594]
[New LWP 7118]
[New LWP 7111]
[New LWP 7324]
[New LWP 5684]
[New LWP 7384]
[New LWP 5694]
[New LWP 7438]
[New LWP 7086]
[New LWP 6312]
[New LWP 7141]
[New LWP 7328]
[New LWP 7406]
[New LWP 7133]
[New LWP 5744]
[New LWP 7304]
[New LWP 7293]
[New LWP 6412]
[New LWP 7004]
[New LWP 7144]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `freeswitch -nc'.
Program terminated with signal 6, Aborted.
#0  0x00007f8ea0eb0387 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.26-21.el7.x86_64 flac-libs-1.3.0-5.el7_1.x86_64 glibc-2.17-317.el7.x86_64 gsm-1.0.13-11.el7.x86_64 jbigkit-libs-2.0-11.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-50.el7.x86_64 ldns-1.6.16-10.el7.x86_64 libcom_err-1.42.9-19.el7.x86_64 libcurl-7.29.0-59.el7_9.1.x86_64 libedit-3.0-12.20121213cvs.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libidn-1.28-4.el7.x86_64 libjpeg-turbo-1.2.90-8.el7.x86_64 libogg-1.3.0-7.el7.x86_64 libselinux-2.5-15.el7.x86_64 libsndfile-1.0.25-12.el7.x86_64 libssh2-1.8.0-4.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 libtiff-4.0.3-35.el7.x86_64 libuuid-2.23.2-65.el7.x86_64 libvorbis-1.3.3-8.el7.1.x86_64 lua-5.1.4-15.el7.x86_64 ncurses-libs-5.9-14.20130511.el7_4.x86_64 nspr-4.25.0-2.el7_9.x86_64 nss-3.53.1-3.el7_9.x86_64 nss-softokn-freebl-3.53.1-6.el7_9.x86_64 nss-util-3.53.1-1.el7_9.x86_64 openldap-2.4.44-5.el7.x86_64 openssl-libs-1.0.2k-21.el7_9.x86_64 opus-1.1-1.el7.centos.x86_64 pcre-8.32-17.el7.x86_64 speex-1.2-0.19.rc1.el7.x86_64 sqlite-3.7.17-8.el7_7.1.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb)

run "bt"(gdb) bt
#0  0x00007f8ea0eb0387 in raise () from /lib64/libc.so.6
#1  0x00007f8ea0eb1a78 in abort () from /lib64/libc.so.6
#2  0x00007f8ea0ef2ed7 in __libc_message () from /lib64/libc.so.6
#3  0x00007f8ea0f92607 in __fortify_fail () from /lib64/libc.so.6
#4  0x00007f8ea0f90782 in __chk_fail () from /lib64/libc.so.6
#5  0x00007f8ea0f92567 in __fdelt_warn () from /lib64/libc.so.6
#6  0x00007f8e8f3cf095 in ldns_sock_wait () from /lib64/libldns.so.1
#7  0x00007f8e8f3cf57f in ldns_udp_send () from /lib64/libldns.so.1
#8  0x00007f8e8f3cfd1a in ldns_send_buffer () from /lib64/libldns.so.1
#9  0x00007f8e8f3d0029 in ldns_send () from /lib64/libldns.so.1
#10 0x00007f8e8f3d4e9d in ldns_resolver_send_pkt () from /lib64/libldns.so.1
#11 0x00007f8e8f3d52c2 in ldns_resolver_send () from /lib64/libldns.so.1
#12 0x00007f8e8f3d5400 in ldns_resolver_query () from /lib64/libldns.so.1
#13 0x00007f8e8f5fc300 in ldns_lookup (number=number@entry=0x7f8d6c0035a0 "+1362800441519470058", root=root@entry=0x1432f00 "e164.org", server_name=server_name@entry=0x7f8b89b1aa10, 
    results=results@entry=0x7f8b89b1ab08) at mod_enum.c:511
#14 0x00007f8e8f5fc52a in enum_lookup (root=0x1432f00 "e164.org", in=<optimized out>, results=results@entry=0x7f8b89b1ab08, channel=channel@entry=0x7f8b788ace40, 
    session=session@entry=0x7f8b788aed68) at mod_enum.c:624
#15 0x00007f8e8f5fc6f7 in enum_dialplan_hunt (session=0x7f8b788aed68, arg=<optimized out>, caller_profile=0x7f8b87cf8220) at mod_enum.c:645
#16 0x00007f8ea363c937 in switch_core_standard_on_routing (session=0x7f8b788aed68) at src/switch_core_state_machine.c:281
#17 switch_core_session_run (session=0x7f8b788aed68) at src/switch_core_state_machine.c:643
#18 0x00007f8ea3634d6e in switch_core_session_thread (thread=<optimized out>, obj=0x7f8b788aed68) at src/switch_core_session.c:1709
#19 0x00007f8ea36307d3 in switch_core_session_thread_pool_worker (thread=0x7f8d5c0e9060, obj=<optimized out>) at src/switch_core_session.c:1772
#20 0x00007f8ea3902680 in dummy_worker (opaque=0x7f8d5c0e9060) at threadproc/unix/thread.c:151
#21 0x00007f8ea1924ea5 in start_thread () from /lib64/libpthread.so.0
#22 0x00007f8ea0f7896d in clone () from /lib64/libc.so.6

(gdb) bt full
(gdb) bt full
#0  0x00007f8ea0eb0387 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007f8ea0eb1a78 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007f8ea0ef2ed7 in __libc_message () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007f8ea0f92607 in __fortify_fail () from /lib64/libc.so.6
No symbol table info available.
#4  0x00007f8ea0f90782 in __chk_fail () from /lib64/libc.so.6
No symbol table info available.
#5  0x00007f8ea0f92567 in __fdelt_warn () from /lib64/libc.so.6
No symbol table info available.
#6  0x00007f8e8f3cf095 in ldns_sock_wait () from /lib64/libldns.so.1
No symbol table info available.
#7  0x00007f8e8f3cf57f in ldns_udp_send () from /lib64/libldns.so.1
No symbol table info available.
#8  0x00007f8e8f3cfd1a in ldns_send_buffer () from /lib64/libldns.so.1
No symbol table info available.
#9  0x00007f8e8f3d0029 in ldns_send () from /lib64/libldns.so.1
No symbol table info available.
#10 0x00007f8e8f3d4e9d in ldns_resolver_send_pkt () from /lib64/libldns.so.1
No symbol table info available.
#11 0x00007f8e8f3d52c2 in ldns_resolver_send () from /lib64/libldns.so.1
No symbol table info available.
#12 0x00007f8e8f3d5400 in ldns_resolver_query () from /lib64/libldns.so.1
No symbol table info available.
#13 0x00007f8e8f5fc300 in ldns_lookup (number=number@entry=0x7f8d6c0035a0 "+1362800441519470058", root=root@entry=0x1432f00 "e164.org", server_name=server_name@entry=0x7f8b89b1aa10, 
    results=results@entry=0x7f8b89b1ab08) at mod_enum.c:511
        res = 0x7f8d6c0599f0
        domain = 0x7f8d6c009eb0
        p = 0x0
        naptr = 0x0
        s = LDNS_STATUS_OK
        status = SWITCH_STATUS_FALSE
        name = <optimized out>
        inameserver = <optimized out>
        added_server = <optimized out>
        __func__ = "ldns_lookup"
        __PRETTY_FUNCTION__ = "ldns_lookup"
#14 0x00007f8e8f5fc52a in enum_lookup (root=0x1432f00 "e164.org", in=<optimized out>, results=results@entry=0x7f8b89b1ab08, channel=channel@entry=0x7f8b788ace40, 
---Type <return> to continue, or q <return> to quit---
    session=session@entry=0x7f8b788aed68) at mod_enum.c:624
        mnum = 0x7f8d6c0035a0 "+1362800441519470058"
        mroot = 0x0
        p = <optimized out>
        server = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}
        inameserver = <optimized out>
        argv = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}
        argc = <optimized out>
        x = <optimized out>
        enum_nameserver_dup = <optimized out>
        enum_nameserver = 0x0
        __func__ = "enum_lookup"
#15 0x00007f8e8f5fc6f7 in enum_dialplan_hunt (session=0x7f8b788aed68, arg=<optimized out>, caller_profile=0x7f8b87cf8220) at mod_enum.c:645
        extension = 0x0
        results = 0x0
        rp = <optimized out>
        channel = 0x7f8b788ace40
        dp = <optimized out>
        __func__ = "enum_dialplan_hunt"
#16 0x00007f8ea363c937 in switch_core_standard_on_routing (session=0x7f8b788aed68) at src/switch_core_state_machine.c:281
        dpname = <optimized out>
        dparg = 0x0
        dp = {0x7f8d6c06b190 "enum", 0x0 <repeats 24 times>}
        argc = <optimized out>
        x = <optimized out>
        count = 1
        extension = 0x0
        dpstr = 0x7f8d6c06b190 "enum"
        dialplan_interface = 0x14362e0
        caller_profile = <optimized out>
        expanded = 0x7f8d6c06b190 "enum"
#17 switch_core_session_run (session=0x7f8b788aed68) at src/switch_core_state_machine.c:643
        global_proceed = <optimized out>
        index = <optimized out>
        proceed = <optimized out>
        do_extra_handlers = 1
        ptr = <optimized out>
        rstatus = <optimized out>
        state = <optimized out>
        midstate = CS_ROUTING
---Type <return> to continue, or q <return> to quit---
        endstate = <optimized out>
        endpoint_interface = <optimized out>
        driver_state_handler = <optimized out>
        application_state_handler = <optimized out>
        new_loops = 473
        __PRETTY_FUNCTION__ = "switch_core_session_run"
        __func__ = "switch_core_session_run"
#18 0x00007f8ea3634d6e in switch_core_session_thread (thread=<optimized out>, obj=0x7f8b788aed68) at src/switch_core_session.c:1709
        session = 0x7f8b788aed68
        event = 0x0
        event_str = 0x0
        val = <optimized out>
        __func__ = "switch_core_session_thread"
        __PRETTY_FUNCTION__ = "switch_core_session_thread"
#19 0x00007f8ea36307d3 in switch_core_session_thread_pool_worker (thread=0x7f8d5c0e9060, obj=<optimized out>) at src/switch_core_session.c:1772
        td = 0x7f8b78833408
        pop = 0x7f8b78833408
        check_status = <optimized out>
        node = <optimized out>
        pool = 0x7f8d5c0e8e08
        __func__ = "switch_core_session_thread_pool_worker"
#20 0x00007f8ea3902680 in dummy_worker (opaque=0x7f8d5c0e9060) at threadproc/unix/thread.c:151
        thread = 0x7f8d5c0e9060
#21 0x00007f8ea1924ea5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#22 0x00007f8ea0f7896d in clone () from /lib64/libc.so.6
No symbol table info available.

**Comment by mjerris** [comment] 2021-01-22 07:58
duplicate of https://github.com/signalwire/freeswitch/issues/1037.  This crash is in libldns not freeswitch

**Closed by mjerris** 2021-01-22 07:58 UTC
Labels: bug

**Comment by yaoshenshen** [comment] 2021-01-22 08:21
> libldns

which I should upgrade libldns from ldns-devel-1.6.16 to high version

**Comment by yaoshenshen** [comment] 2021-01-22 08:21
> duplicate of #1037. This crash is in libldns not freeswitch

which I should upgrade libldns from ldns-devel-1.6.16 to high version

**Comment by mjerris** [comment] 2021-01-22 16:35
follow current install instructions on a current freeswitch version.

**Comment by BlueCoffee-SG** [comment] 2021-07-22 07:50
#0  0x00007fe934519387 in raise () from /lib64/libc.so.6
#1  0x00007fe93451aa78 in abort () from /lib64/libc.so.6
#2  0x00007fe93455bf67 in __libc_message () from /lib64/libc.so.6
#3  0x00007fe9345fb697 in __fortify_fail () from /lib64/libc.so.6
#4  0x00007fe9345f9812 in __chk_fail () from /lib64/libc.so.6
#5  0x00007fe9345fb5f7 in __fdelt_warn () from /lib64/libc.so.6
#6  0x00007fe92df33095 in ldns_sock_wait () from /lib64/libldns.so.1
#7  0x00007fe92df3357f in ldns_udp_send () from /lib64/libldns.so.1
#8  0x00007fe92df33d1a in ldns_send_buffer () from /lib64/libldns.so.1
#9  0x00007fe92df34029 in ldns_send () from /lib64/libldns.so.1
#10 0x00007fe92df38e9d in ldns_resolver_send_pkt () from /lib64/libldns.so.1
#11 0x00007fe92df392c2 in ldns_resolver_send () from /lib64/libldns.so.1
#12 0x00007fe92df39400 in ldns_resolver_query () from /lib64/libldns.so.1
#13 0x00007fe92e160360 in ldns_lookup (number=number@entry=0x7fe84c1d3120 "+162", root=root@entry=0x7fe924011540 "e164.org", server_name=server_name@entry=0x7fe816a12a00, results=results@entry=0x7fe816a12af8)
    at mod_enum.c:513
#14 0x00007fe92e16058a in enum_lookup (root=0x7fe924011540 "e164.org", in=<optimized out>, results=results@entry=0x7fe816a12af8, channel=channel@entry=0x7fe9155be910, session=session@entry=0x7fe914f3b6f8)
    at mod_enum.c:626
#15 0x00007fe92e160757 in enum_dialplan_hunt (session=0x7fe914f3b6f8, arg=<optimized out>, caller_profile=0x7fe8902fa428) at mod_enum.c:647
#16 0x00007fe938287bab in switch_core_standard_on_routing (session=0x7fe914f3b6f8) at src/switch_core_state_machine.c:282
#17 switch_core_session_run (session=0x7fe914f3b6f8) at src/switch_core_state_machine.c:644
#18 0x00007fe93827ffce in switch_core_session_thread (thread=<optimized out>, obj=0x7fe914f3b6f8) at src/switch_core_session.c:1709
#19 0x00007fe93827ba33 in switch_core_session_thread_pool_worker (thread=0x7fe9151a6a10, obj=<optimized out>) at src/switch_core_session.c:1772
#20 0x00007fe938582ce0 in dummy_worker (opaque=0x7fe9151a6a10) at threadproc/unix/thread.c:151
#21 0x00007fe9348b8ea5 in start_thread () from /lib64/libpthread.so.0
#22 0x00007fe9345e19fd in clone () from /lib64/libc.so.6

the  freeswitch is 1.10.5version  base on centos 7.4 CentOS  7.5 x64
