### ISSUE TITLE
crashed FreeSWITCH version: 1.10.3-release+git~20200511T105455Z~129de34d84~64bit[Program terminated with signal SIGSEGV, Segmentation fault.]

### ISSUE THREAD

**Issue by bee-jarvis** [signalwire/freeswitch#635] opened 2020-05-14 17:01 UTC
as I observed , if 1000 members entered to conference its abnormally crashed.
[20200506T065202Z-bt.txt](https://github.com/signalwire/freeswitch/files/4629827/20200506T065202Z-bt.txt)

**Comment by mjerris** [comment] 2020-05-14 17:04
in gdb:
frame 4
print *session

**Comment by bee-jarvis** [comment] 2020-05-14 17:09
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/freeswitch/bin/freeswitch -u root -g root -ncwait -nonat'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __pthread_rwlock_wrlock_full (abstime=0x0, rwlock=0x8) at pthread_rwlock_common.c:576
576     pthread_rwlock_common.c: No such file or directory.
[Current thread is 1 (Thread 0x1463fc7d0700 (LWP 29564))]
(gdb) frame 4
#4  0x0000146c59da4a5d in listener_run (thread=<optimized out>, obj=0x146bf4493798) at mod_event_socket.c:2788
2788            switch_thread_rwlock_wrlock(listener->rwlock);
(gdb) print *session
$1 = {pool = 0x0, thread = 0x0, thread_id = 0, endpoint_interface = 0x0, id = 0, flags = SSF_NONE, channel = 0x0, event_hooks = {outgoing_channel = 0x0,
    receive_message = 0x0, receive_event = 0x0, read_frame = 0x0, video_read_frame = 0x0, write_frame = 0x0, video_write_frame = 0x0, text_write_frame = 0x0,
    text_read_frame = 0x0, kill_channel = 0x0, send_dtmf = 0x0, recv_dtmf = 0x0, state_change = 0x0, state_run = 0x0}, read_codec = 0x0, real_read_codec = 0x0,
  write_codec = 0x0, real_write_codec = 0x0, video_read_codec = 0x0, video_write_codec = 0x0, read_impl = {codec_type = SWITCH_CODEC_TYPE_AUDIO, ianacode = 0 '\000',
    iananame = 0x0, fmtp = 0x0, samples_per_second = 0, actual_samples_per_second = 0, bits_per_second = 0, microseconds_per_packet = 0, samples_per_packet = 0,
    decoded_bytes_per_packet = 0, encoded_bytes_per_packet = 0, number_of_channels = 0 '\000', codec_frames_per_packet = 0, init = 0x0, encode = 0x0, decode = 0x0,
    encode_video = 0x0, decode_video = 0x0, codec_control = 0x0, destroy = 0x0, codec_id = 0, impl_id = 0, modname = 0x0, next = 0x0}, real_read_impl = {
    codec_type = SWITCH_CODEC_TYPE_AUDIO, ianacode = 0 '\000', iananame = 0x0, fmtp = 0x0, samples_per_second = 0, actual_samples_per_second = 0, bits_per_second = 0,
    microseconds_per_packet = 0, samples_per_packet = 0, decoded_bytes_per_packet = 0, encoded_bytes_per_packet = 0, number_of_channels = 0 '\000',
    codec_frames_per_packet = 0, init = 0x0, encode = 0x0, decode = 0x0, encode_video = 0x0, decode_video = 0x0, codec_control = 0x0, destroy = 0x0, codec_id = 0,
    impl_id = 0, modname = 0x0, next = 0x0}, write_impl = {codec_type = SWITCH_CODEC_TYPE_AUDIO, ianacode = 0 '\000', iananame = 0x0, fmtp = 0x0,
    samples_per_second = 0, actual_samples_per_second = 0, bits_per_second = 0, microseconds_per_packet = 0, samples_per_packet = 0, decoded_bytes_per_packet = 0,
    encoded_bytes_per_packet = 0, number_of_channels = 0 '\000', codec_frames_per_packet = 0, init = 0x0, encode = 0x0, decode = 0x0, encode_video = 0x0,
    decode_video = 0x0, codec_control = 0x0, destroy = 0x0, codec_id = 0, impl_id = 0, modname = 0x0, next = 0x0}, video_read_impl = {
    codec_type = SWITCH_CODEC_TYPE_AUDIO, ianacode = 0 '\000', iananame = 0x0, fmtp = 0x0, samples_per_second = 0, actual_samples_per_second = 0, bits_per_second = 0,
    microseconds_per_packet = 0, samples_per_packet = 0, decoded_bytes_per_packet = 0, encoded_bytes_per_packet = 0, number_of_channels = 0 '\000',
    codec_frames_per_packet = 0, init = 0x0, encode = 0x0, decode = 0x0, encode_video = 0x0, decode_video = 0x0, codec_control = 0x0, destroy = 0x0, codec_id = 0,
    impl_id = 0, modname = 0x0, next = 0x0}, video_write_impl = {codec_type = SWITCH_CODEC_TYPE_AUDIO, ianacode = 0 '\000', iananame = 0x0, fmtp = 0x0,
    samples_per_second = 0, actual_samples_per_second = 0, bits_per_second = 0, microseconds_per_packet = 0, samples_per_packet = 0, decoded_bytes_per_packet = 0,
    encoded_bytes_per_packet = 0, number_of_channels = 0 '\000', codec_frames_per_packet = 0, init = 0x0, encode = 0x0, decode = 0x0, encode_video = 0x0,
    decode_video = 0x0, codec_control = 0x0, destroy = 0x0, codec_id = 0, impl_id = 0, modname = 0x0, next = 0x0}, read_resampler = 0x0, write_resampler = 0x0,
  mutex = 0x0, stack_count_mutex = 0x0, resample_mutex = 0x0, codec_read_mutex = 0x0, codec_write_mutex = 0x146bf4fdc340, video_codec_read_mutex = 0x146bf4fdc560,
  video_codec_write_mutex = 0x146bf4fdc780, cond = 0x146bf4fdc9a0, frame_read_mutex = 0x146bf4fdc340, rwlock = 0x146bf4fdc780, io_rwlock = 0x146bf4fdcbc0, streams = {
    0x146bf4fdd000, 0x146bf4fdc340, 0x50000110f, 0x0, 0x0, 0x146bf44eec00, 0x880, 0x146bf44eec00, 0x0, 0x0, 0x3f80000000000000, 0x3f8000003f800000 <repeats 31 times>,
    0x3f800000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x100000001, 0x200000001, 0x200000002, 0x300000002, 0x300000003, 0x400000004, 0x500000005, 0x500000005,
    0x500000005, 0x500000005, 0x500000005, 0x100000005, 0x100000001, 0x200000002, 0x200000002, 0x300000003, 0x400000003, 0x500000004, 0x500000005, 0x500000005,
    0x500000005, 0x500000005, 0x500000005, 0x100000001, 0x200000001, 0x200000002, 0x300000002, 0x300000003, 0x500000004, 0x500000005, 0x500000005, 0x500000005,
    0x500000005, 0x500000005, 0x100000005, 0x200000001, 0x200000002, 0x300000003, 0x400000003, 0x500000005, 0x500000005, 0x500000005, 0x500000005, 0x500000005,
    0x500000005, 0x500000005, 0x100000001, 0x200000002, 0x300000002, 0x300000003, 0x500000004, 0x500000005, 0x500000005, 0x500000005, 0x500000005, 0x500000005,
    0x500000005, 0x100000005, 0x200000001, 0x200000002, 0x300000003, 0x400000003, 0x500000005, 0x500000005, 0x500000005, 0x500000005, 0x500000005, 0x500000005,
    0x500000005, 0x100000001, 0x200000002, 0x300000002, 0x300000003, 0x500000004, 0x500000005, 0x500000005, 0x500000005, 0x500000005}, stream_count = 5,
  uuid_str = "\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\001\000\000\000\001\000\000\000\002\000\000\000\002\000\000\000\002\000\000\000\003\000\000\000\003\000\000\000\003\000\000\000\004\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\001\000\000\000\002\000\000\000\002\000\000\000\003\000\000\000\004\000\000\000\004\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000"..., private_info = {
    0x200000001, 0x300000002}, event_queue = 0x500000004, message_queue = 0x500000005, signal_data_queue = 0x500000005, private_event_queue = 0x500000005,
  private_event_queue_pri = 0x100000005, bug_rwlock = 0x200000001, bugs = 0x300000002, app_log = 0x500000004, stack_count = 5, raw_write_buffer = 0x500000005,
  raw_write_frame = {codec = 0x500000005, source = 0x100000005 <error: Cannot access memory at address 0x100000005>, packet = 0x200000001, packetlen = 2,
    extra_data = 0x500000004, data = 0x500000005, datalen = 5, buflen = 5, samples = 5, rate = 5, channels = 5, payload = 1 '\001', timestamp = 1, seq = 2, ssrc = 2,
    m = (SWITCH_TRUE | unknown: 2), flags = 5, user_data = 0x500000005, pmap = 0x500000005, img = 0x500000005, geometry = {w = 5, h = 1, x = 1, y = 2, z = 2, M = 3,
      X = 5}}, enc_write_frame = {codec = 0x500000005, source = 0x500000005 <error: Cannot access memory at address 0x500000005>, packet = 0x500000005, packetlen = 5,
    extra_data = 0x200000001, data = 0x300000002, datalen = 5, buflen = 5, samples = 5, rate = 5, channels = 5, payload = 5 '\005', timestamp = 5, seq = 5, ssrc = 5,
--Type <RET> for more, q to quit, c to continue without paging--
    m = SWITCH_TRUE, flags = 1, user_data = 0x300000002, pmap = 0x500000005, img = 0x500000005, geometry = {w = 5, h = 5, x = 5, y = 5, z = 5, M = 1, X = 2}},
  raw_write_buf = "\004\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\005\000\000\000\363\004\065E\360\067\030E\000\000\000E\375D\327D\363\004\265D\360\067\230D\000\000\200D\375DWD\363\004\065D\360\067\030D\000\000\000D\375D\327C\363\004\265C\360\067\230C\000\000\200C\375DWC\363\004\065C\360\067\030C\000\000\000C\375D\327B\363\004\265B\360\067\230B\000\000\200B\375DWB\363\004\065B\360\067\030B\000\000\000B\375D\327A\363\004\265A\360\067\230A\000\000\200A\375DWA\363\004\065A\360\067\030A\000\000\000A\375D\327@\363\004\265@\360\067\230@\000\000\200@"...,
  enc_write_buf = "\334Y\217\065\071\216c5h\234\064\065\334Y\017\065\000\000\000\000\071\216\343?h\234\264?\334Y\217?9\216c?h\234\064?\334Y\017?9\216\343>h\234\264>\334Y\217>9\216c>h\234\064>\334Y\017>9\216\343=h\234\264=\334Y\217=9\216c=h\234\064=\334Y\017=9\216\343<h\234\264<\334Y\217<9\216c<h\234\064<\334Y\017<9\216\343;h\234\264;\334Y\217;9\216c;h\234\064;\334Y\017;9\216\343:h\234\264:\334Y\217:9\216c:h\234\064:\334Y\017:9\216\343\071h\234\264\071\334Y\217\071\071\216c9h\234\064\071\334Y\017\071\071\216\343\070h\234\264\070\334Y\217\070"..., raw_read_buffer = 0x0, raw_read_frame = {codec = 0x0, source = 0x0, packet = 0x0, packetlen = 0, extra_data = 0x0,
    data = 0x0, datalen = 0, buflen = 0, samples = 0, rate = 0, channels = 0, payload = 0 '\000', timestamp = 0, seq = 0, ssrc = 0, m = SWITCH_FALSE, flags = 0,
    user_data = 0x0, pmap = 0x0, img = 0x0, geometry = {w = 0, h = 0, x = 0, y = 0, z = 0, M = 0, X = 0}}, enc_read_frame = {codec = 0x0, source = 0x0, packet = 0x0,
    packetlen = 0, extra_data = 0x0, data = 0x0, datalen = 0, buflen = 0, samples = 0, rate = 0, channels = 0, payload = 0 '\000', timestamp = 0, seq = 0, ssrc = 0,
    m = SWITCH_FALSE, flags = 0, user_data = 0x0, pmap = 0x0, img = 0x0, geometry = {w = 0, h = 0, x = 0, y = 0, z = 0, M = 0, X = 0}},
  raw_read_buf = '\000' <repeats 608 times>...,
  enc_read_buf = "\021\000\016\000\006\000\001\000\000\000\000\000\001\000\376\377\003\000\a\000\000\000\377\377\366\377\373\377\003\000\364\377\370\377\372\377\366\377\364\377\362\377\000\000\373\377\374\377\366\377\373\377\b\000\b\000\b\000\374\377\001\000\006\000\017\000\t\000\a\000\373\377\365\377\361\377\370\377\371\377\365\377\370\377\375\377\356\377\345\377\356\377\365\377\371\377\376\377\375\377\001\000\a\000\022\000\r\000\v\000\021\000\031\000\025\000\025\000\026\000\030\000\026\000\030\000\024\000\001\000\003\000\000\000\371\377\363\377\364\377\360\377\350\377\351\377\354\377\360\377\361\377\367\377\002\000\371\377\376\377\372\377\003\000\b\000\f\000\f\000\a\000\376\377\377\377\376\377\377\377\375\377\372\377\376\377\370\377\364\377\366\377\371\377\377\377\372\377\373\377"...,
  video_raw_write_buffer = 0x7000600020003, video_raw_write_frame = {codec = 0xc000a00080009,
    source = 0x8000e000d0010 <error: Cannot access memory at address 0x8000e000d0010>, packet = 0x6000d00050005, packetlen = 131074, extra_data = 0xffeefff3fff3ffef,
    data = 0xfff3ffefffeaffe9, datalen = 4294574067, buflen = 4294967290, samples = 262145, rate = 8, channels = 131071, payload = 4 '\004', timestamp = 4294901758,
    seq = 4, ssrc = 131065, m = (SWITCH_TRUE | unknown: 589832), flags = 5, user_data = 0x3000100040002, pmap = 0x200020007fffe, img = 0xa00080000, geometry = {
      w = 458758, h = 65540, x = 65535, y = 4, z = -327681, M = -458758, X = -393225}}, video_raw_read_buffer = 0xfff7fffbfffdfff7, video_raw_read_frame = {
    codec = 0xfffb0002fffafff6, source = 0x1fffffffefffc <error: Cannot access memory at address 0x1fffffffefffc>, packet = 0xfffdfffbfffc, packetlen = 4294574076,
    extra_data = 0x600000002fffe, data = 0x7000700040000, datalen = 851977, buflen = 720909, samples = 393221, rate = 458757, channels = 655364, payload = 3 '\003',
    timestamp = 4294967295, seq = 5, ssrc = 4294770680, m = (SWITCH_TRUE | unknown: 4294836222), flags = 65527, user_data = 0xffff000300040000,
    pmap = 0x1000100050002, img = 0xfffcfffe00040002, geometry = {w = -327690, h = -196615, x = -196612, y = 65537, z = 589826, M = 327692, X = 524294}}, bug_codec = {
    codec_interface = 0xfff6fffc0000ffff, implementation = 0xffebffe9fff1fff0,
    fmtp_in = 0xffefffecffe6ffe8 <error: Cannot access memory at address 0xffefffecffe6ffe8>,
    fmtp_out = 0xfffefffffff6fff3 <error: Cannot access memory at address 0xfffefffffff6fff3>, flags = 786437, memory_pool = 0xf00130013000b,
    private_info = 0xa001200140011, agreed_pt = 13 '\r', mutex = 0x10000f000e000c, next = 0x300040005000a, session = 0xfffcfff9fffcfffd,
    cur_frame = 0xffecfff2fffbfffb}, read_frame_count = 4293918704, track_duration = 4293591022, track_id = 4293722089, loglevel = 4293853160, soft_lock = 4294442988,
  dmachine = {0xfffc0000fff9fffa, 0x100030001fffc}, plc = 0x500030005fffe, media_handle = 0x9000d000b000b, decoder_errors = 1179657,
  video_read_callback = 0xd001200120009, video_read_user_data = 0xd000d000e000e, text_read_callback = 0x6000b000f000b, text_read_user_data = 0xfffdfffcfffe0000,
  io_override = 0xfffbfffe00000004, sdata = 0xffedfff0fff6fffa, text_buffer = 0xfff2ffeffff1fff1, text_line_buffer = 0xfff7fffbfff4fff1,
  text_mutex = 0xfffefffafffffffb}

**Comment by mjerris** [comment] 2020-05-14 19:20
can you please test out https://github.com/signalwire/freeswitch/pull/636 and see if that corrects the issue?

**Comment by andywolk** [comment] 2020-05-14 23:15
Duplicate of https://github.com/signalwire/freeswitch/issues/612

**Closed** 2020-05-18 17:22 UTC
Labels: bug
