### ISSUE TITLE
Cant start freeswitch .:. ERROR: Failed to set SCHED_FIFO scheduler (Operation not permitted)

### ISSUE THREAD

**Issue by Svenchenchen** [signalwire/freeswitch#758] opened 2020-07-27 20:28 UTC
I have installed freeswitch on a fresh centos7.8 and I always get the error message.
freeswitch was installed from the rpm package according to the instructions.

```
ERROR: Failed to set SCHED_FIFO scheduler (Operation not permitted)
ERROR: Could not set nice level
```

Sometimes there is an entry:
`Cannot Initialize [[error near line 8161]: unexpected closing tag </condition>]`
in the journal

**Comment by mjerris** [comment] 2020-07-27 20:43
this is a permissions issue of some sort.  how are you starting freeswitch?

**Comment by Svenchenchen** [comment] 2020-07-27 20:58
Hello I'm starting Freeswitch as a service. I started it in the foreground and always get the same error message

**Comment by Svenchenchen** [comment] 2020-07-27 21:06
under root

**Comment by ontur00** [comment] 2020-08-24 12:08
Hi that someone did with that problem or maybe have advice what to do ?

[root@localhost ~]# fs_cli
[ERROR] fs_cli.c:1691 main() Error Connecting []

[root@localhost ~]# service freeswitch status
Redirecting to /bin/systemctl status freeswitch.service
● freeswitch.service - FreeSWITCH
   Loaded: loaded (/usr/lib/systemd/system/freeswitch.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since pon 2020-08-24 12:20:04 CEST; 1h 46min ago
 Main PID: 11988 (code=exited, status=255)

sie 24 12:20:03 localhost systemd[1]: Started FreeSWITCH.
sie 24 12:20:04 localhost freeswitch[11988]: ERROR: Failed to set SCHED_FIFO scheduler (Operation not permitted)
sie 24 12:20:04 localhost freeswitch[11988]: ERROR: Could not set nice level
sie 24 12:20:04 localhost freeswitch[11988]: Cannot Initialize [[error near line 8810]: unexpected closing tag </condition>]
sie 24 12:20:04 localhost systemd[1]: freeswitch.service: main process exited, code=exited, status=255/n/a
sie 24 12:20:04 localhost systemd[1]: Unit freeswitch.service entered failed state.
sie 24 12:20:04 localhost systemd[1]: freeswitch.service failed.

**Comment by dragos-oancea** [comment] 2020-08-24 12:38
Solve the xml config issue first: "Cannot Initialize [[error near line 8810]: unexpected closing tag ]"

**Comment by ontur00** [comment] 2020-08-24 16:06
> Solve the xml config issue first: "Cannot Initialize [[error near line 8810]: unexpected closing tag ]"
Where i can find config ?    /etc/freeswitch/*.xml ?  The name of this file and which directory ?

**Comment by boteman** [comment] 2020-08-24 17:45
The error line number refers to the master configuration file 
freeswitch.xml.fsxml
which is a concatenation of all the configuration files. Search for that file, find the line number mentioned above, and determine which configuration file contains the error. Edit the individual configuration file, not the freeswitch.xml.fsxml which changes every time FS starts.

**Comment by ontur00** [comment] 2020-08-25 09:14
Ok i find freeswitch.xml.fsxml at directory /var/log/freeswitch/freeswitch.xml.fsxml 
I find line 8810 with string  ""
After try find string at "" at some dir.


grep -rnw '/usr/ictcore/' -e '<action application="lua" data="/usr/ictcore/bin/freeswitch/application.lua 0 inbound success" />'

I found this line at /usr/ictcore/etc/freeswitch/dialplan/ictcore.xml

xml look like https://ctxt.io/2/AADAt5IhFA

or

`<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dialplan>

<include>
  
  <context name="ictcore">
    <extension name="application_inbound">
      <condition field="destination_number" expression="^\+?(\d+)$">
        <action application="lua" data="/usr/ictcore/bin/freeswitch/application.lua 0 inbound success" />
        <action application="hangup"/>
      </condition>
    </extension>
    <extension name="application_inbound_to">
     <condition field="${sip_to_user}" expression="^\+?(\d+)$">
       <action application="set" data="destination_number=${sip_to_user}">
       <action application="lua" data="/usr/ictcore/bin/freeswitch/application.lua 0 inbound success" />
       <action application="hangup"/>
     </condition>
    </extension>
  </context>
  
  <context name="ictcore_fail">
    <extension name="app_originate_fail">
      <condition field="${originate_disposition}" expression="^(.*)$">
        <action application="lua" data="/usr/ictcore/bin/freeswitch/spool_failed.lua ${spool_id} ${application_id} $1" />
        <action application="hangup"/>
      </condition>
    </extension>
  </context>
  
  <context name="ictcore_gateway">
    <X-PRE-PROCESS cmd="include" data="/usr/ictcore/etc/freeswitch/dialplan/provider/*.xml"/>
<extension name="catch_invalid">
      <condition field="destination_number" expression=".*">
        <action application="playback" data="sounds/invalid_extension.wav"/>
        <action application="hangup"/>
      </condition>
    </extension>
  </context>
  
  <X-PRE-PROCESS cmd="include" data="/usr/ictcore/etc/freeswitch/dialplan/user/*.xml"/>
</include>
`

**Comment by ontur00** [comment] 2020-08-26 08:57
Ok i solved the problem 
But now i have new one afeter type service freeswitch status

Redirecting to /bin/systemctl status freeswitch.service
● freeswitch.service - FreeSWITCH
   Loaded: loaded (/usr/lib/systemd/system/freeswitch.service; enabled; vendor preset: disabled)
   Active: active (running) since czw 2020-08-20 14:34:16 CEST; 21h ago
 Main PID: 2037 (freeswitch)
   CGroup: /system.slice/freeswitch.service
           └─2037 /usr/bin/freeswitch -nc -nf

sie 20 14:34:16 localhost.localdomain systemd[1]: Started FreeSWITCH.
sie 20 14:34:16 localhost.localdomain freeswitch[2037]: **ERROR: Failed to set SCHED_FIFO scheduler (Operation not permitted)**
sie 20 14:34:16 localhost.localdomain freeswitch[2037]: **ERROR: Could not set nice level**

What can i do with this errors ?

**Comment by yuyujulin** [comment] 2020-12-02 15:39
same error。 run freeswitch by ‘systemctl start freeswitch’ under root. it gives me:

```sh
[root@localhost freeswitch]# systemctl status freeswitch
● freeswitch.service - FreeSWITCH
   Loaded: loaded (/usr/lib/systemd/system/freeswitch.service; enabled; vendor preset: disabled)
   Active: active (running) since 三 2020-12-02 23:11:54 CST; 23min ago
 Main PID: 57658 (freeswitch)
   CGroup: /system.slice/freeswitch.service
           └─57658 /usr/bin/freeswitch -nc -nf

12月 02 23:11:54 localhost.localdomain systemd[1]: Started FreeSWITCH.
12月 02 23:11:54 localhost.localdomain freeswitch[57658]: ERROR: Failed to set SCHED_FIFO scheduler (Operation not permitted)
12月 02 23:11:54 localhost.localdomain freeswitch[57658]: ERROR: Could not set nice level

```

**Comment by thechonta** [comment] 2021-01-11 12:05
@ontur00 
How culd you solv the Problem with the xml and the /condition tag?
I try to run the ictfax centos7 arcording to the officiel documentation but the system does not work at all.
No fax can be send becaus freeswitch does not work.....

**Comment by ChrisZhangJin** [comment] 2021-08-06 09:49
hi all, i added non-root user freeswitch:freeswitch in centos, and run freeswitch with user/group freeswitch:freeswitch.  the same issue happened.  

Does it mean that it must use root to run freeswitch??


I just use the command 'freeswitch -nonat' to run.

**Comment by mjerris** [comment] 2021-08-06 13:57
you can use command line params to drop permissions to a diff user

**Closed by mjerris** 2021-08-06 13:57 UTC

**Comment by whosgonna** [comment] 2021-08-25 16:31
The issue looks to arise from the .rpm for Freeswitch.  After following these [instructions to install](https://freeswitch.org/confluence/display/FREESWITCH/CentOS+7+and+RHEL+7), I have the following systemd unit file for the service.  The  user is set here (`User=Freeswitch`).  This should probably be done more like the the debian systemd unit file, setting `Environment="USER=freeswitch"`, and then passing `${USER}` to freeswitch as a parameter in the ExecStart.


```
[root@freeswitch01 ben]# cat /usr/lib/systemd/system/freeswitch.service
[Unit]
Description=FreeSWITCH
After=syslog.target network.target
After=postgresql.service postgresql-9.3.service postgresql-9.4.service mysqld.service httpd.service

[Service]
User=freeswitch
EnvironmentFile=-/etc/sysconfig/freeswitch
# RuntimeDirectory is not yet supported in CentOS 7. A workaround is to use /etc/tmpfiles.d/freeswitch.conf
#RuntimeDirectory=/run/freeswitch
#RuntimeDirectoryMode=0750
WorkingDirectory=/run/freeswitch
ExecStart=/usr/bin/freeswitch -nc -nf $FREESWITCH_PARAMS
ExecReload=/usr/bin/kill -HUP $MAINPID
```

[Install]
WantedBy=multi-user.target
```


It looks like this is setup from [build/freeswitch.service](It looks like this is setup from freeswitch/build/freeswitch.service.  Thoughts on this change?).  Thoughts on this change?

```
[Unit]
Description=FreeSWITCH
After=syslog.target network.target
After=postgresql.service postgresql-9.3.service postgresql-9.4.service mysqld.service httpd.service

[Service]
EnvironmentFile=-/etc/sysconfig/freeswitch
Environment="USER=freeswitch"
# RuntimeDirectory is not yet supported in CentOS 7. A workaround is to use /etc/tmpfiles.d/freeswitch.conf
#RuntimeDirectory=/run/freeswitch
#RuntimeDirectoryMode=0750
WorkingDirectory=/run/freeswitch
ExecStart=/usr/bin/freeswitch -nc -nf -u ${USER} $FREESWITCH_PARAMS
ExecReload=/usr/bin/kill -HUP $MAINPID
```

[Install]
WantedBy=multi-user.target
```

**Comment by whosgonna** [comment] 2021-08-25 16:36
There's also a bit of misunderstanding in the initial issue report.  The failure to start freeswitch appears to be due to misconfiguration. 

The following lines:
```
ERROR: Failed to set SCHED_FIFO scheduler (Operation not permitted)
ERROR: Could not set nice level
```

Are caused by the issue with the systemd unit file.

**Comment by bbslucky** [comment] 2024-10-07 05:15
i meet same question,and i deal it
in freeswitch.service
EnvironmentFile=-/etc/sysconfig/freeswitch
must point to your path ,if build from souce,change it to -/usr/local/freeswitch/etc/freeswitch,that's ok
