### ISSUE TITLE
One of the files.freeswitch.org servers has an invalid certificate

### ISSUE THREAD

**Issue by jimmythedog** [signalwire/freeswitch#401] opened 2020-02-21 07:02 UTC
When the build process attempts to download the sound files from https://files.freeswitch.org, the build randomly fails with "out of date cert" errors

If you execute the following command, you will see that sometimes an old cert (expired Feb 20th 2020)  is returned:
`watch -n1 'echo ""|openssl s_client -verify_quiet -showcerts files.freeswitch.org:443|openssl x509 -noout -enddate'`

**Comment by andywolk** [comment] 2020-02-21 09:11
Thank you for the report! I've restarted our web server.

It’s because there have been orphaned Apache processes which have the old certificate loaded, which don’t get killed when Apache is restarted the normal way.

BTW that's the right command (see `-connect`):
```
watch -n1 'echo ""|openssl s_client -verify_quiet -showcerts -connect files.freeswitch.org:443|openssl x509 -noout -enddate'
```

I'm closing this issue, but leave a comment if the problem is there still.

**Closed by andywolk** 2020-02-21 09:11 UTC
Labels: bug
