### ISSUE TITLE
freeswitch installing error when make or make install

### ISSUE THREAD

**Issue by foermo4-hao** [signalwire/freeswitch#176] opened 2019-12-13 08:57 UTC
make[4]: Nothing to be done for `all'.
make[3]: Nothing to be done for `local-all'.
  CC       src/libfreeswitch_la-switch_apr.lo
  CC       src/libfreeswitch_la-switch_buffer.lo
  CC       src/libfreeswitch_la-switch_caller.lo
  CC       src/libfreeswitch_la-switch_channel.lo
  CC       src/libfreeswitch_la-switch_console.lo
  CC       src/libfreeswitch_la-switch_mprintf.lo
  CC       src/libfreeswitch_la-switch_core_media_bug.lo
  CC       src/libfreeswitch_la-switch_core_timer.lo
  CC       src/libfreeswitch_la-switch_core_asr.lo
  CC       src/libfreeswitch_la-switch_core_event_hook.lo
  CC       src/libfreeswitch_la-switch_core_speech.lo
  CC       src/libfreeswitch_la-switch_core_memory.lo
  CC       src/libfreeswitch_la-switch_core_codec.lo
  CC       src/libfreeswitch_la-switch_core_file.lo
  CC       src/libfreeswitch_la-switch_core_cert.lo
src/switch_core_cert.c:39:20: error: unused function 'switch_ssl_ssl_lock_callback'
      [-Werror,-Wunused-function]
static inline void switch_ssl_ssl_lock_callback(int mode, int type, char *file, int line)
                   ^
src/switch_core_cert.c:49:29: error: unused function 'switch_ssl_ssl_thread_id'
      [-Werror,-Wunused-function]
static inline unsigned long switch_ssl_ssl_thread_id(void)
                            ^
2 errors generated.
make[1]: *** [src/libfreeswitch_la-switch_core_cert.lo] Error 1
make: *** [all] Error 2

**Comment by andywolk** [comment] 2019-12-13 08:59
what os and compiler version?

**Comment by foermo4-hao** [comment] 2019-12-13 09:02
> what os and compiler version?

macOS Mojave 10.14.6 on branch master

**Comment by foermo4-hao** [comment] 2019-12-13 10:26
when I use macOS macFI Installation  
<img width="419" alt="image" src="https://user-images.githubusercontent.com/36944885/70793350-0f974480-1dd6-11ea-949d-3b23ab958529.png">

**Comment by mjerris** [comment] 2019-12-13 16:39
try to update openssl on homebrew and see if it helps

**Comment by foermo4-hao** [comment] 2019-12-16 03:23
> try to update openssl on homebrew and see if it helps

my openssl is lastsd version but not work 
<img width="835" alt="image" src="https://user-images.githubusercontent.com/36944885/70876934-7e52e880-1ff6-11ea-8631-6fcc65e41c3f.png">

**Comment by teresalazar13** [comment] 2020-01-02 13:51
getting the same error

**Comment by 7bp** [comment] 2020-01-02 16:21
I am not a professional on this topic, simply trying out Freeswitch after a long time and ran into the same problem. I simply removed the two mentioned functions from the file `src/switch_core_cert.c` and it compiled quite successful for me.

However, the tests throwing this error now:
```
switch_rtp.c:18:1: error: unknown type name 'uint'; did you mean 'int'?
uint datalen;
^~~~
int
1 error generated.
```

**Comment by akafanfan** [comment] 2020-01-08 13:09
> 我不是这个主题的专业人士，只是在很长一段时间后尝试使用Freeswitch并遇到了同样的问题。我只是从文件中删除了两个提到的函数`src/switch_core_cert.c`，它对我来说编译非常成功。
> 
> 但是，测试现在会引发此错误：
> 
> ```
> switch_rtp.c:18:1: error: unknown type name 'uint'; did you mean 'int'?
> uint datalen;
> ^~~~
> int
> 1 error generated.
> ```
> 
> **编辑：**通过删除所有switch_rtp测试，解决了这一问题。

how to hacked around this by removing all the tests for switch_rtp? edit switch_rtp.c?

**Comment by yjmyzz** [comment] 2020-01-18 06:55
> when I use macOS macFI Installation
> <img alt="image" width="419" src="https://user-images.githubusercontent.com/36944885/70793350-0f974480-1dd6-11ea-949d-3b23ab958529.png">

![image](https://user-images.githubusercontent.com/5262225/72659976-55ad7c80-3a02-11ea-9a2e-d2b6d52a7e44.png)
System Preferences --> Security&Privacy , check the box of "macOS freeswitch Installer" and "terminal"

**Comment by placebokkk** [comment] 2020-02-19 05:50
> when I use macOS macFI Installation
> <img alt="image" width="419" src="https://user-images.githubusercontent.com/36944885/70793350-0f974480-1dd6-11ea-949d-3b23ab958529.png">

For your mac use Chinese charactor '编辑' While the install script want to find the english 'Edit' You could set system language to fix this problem.

**Comment by placebokkk** [comment] 2020-02-19 06:21
@anthmFS  I see you are the Contributor of this file. Could you help look on this. Thanks!

This error is caused by compiler option [-Werror,-Wunused-function]. The compiler treat Warning as Error.

In acutualy, CRYPTO_set_id_callback and CRYPTO_set_locking_callback have been deprecated in openssl library
in

/usr/local/Cellar/node/11.12.0/include/node/openssl/crypto.h

you could see.

line 213
# define CRYPTO_set_locking_callback(func)
line 243
# define CRYPTO_set_id_callback(func)
So switch_ssl_ssl_lock_callback and switch_ssl_ssl_thread_id is not used and [-Werror,-Wunused-function] compiler opt will raise error.

The fix method is below:

remove the definition of switch_ssl_ssl_lock_callback and switch_ssl_ssl_thread_id
set
CRYPTO_set_id_callback(switch_ssl_ssl_thread_id);
CRYPTO_set_locking_callback((void (*)(int, int, const char*, int))switch_ssl_ssl_lock_callback);

to

CRYPTO_set_id_callback(NULL);
CRYPTO_set_locking_callback(NULL);
or just delete this two lines.

**Comment by MarioG-X** [comment] 2020-03-20 17:47
Sorry for the #518 duplicate. I found this before Christmas and worked all Xmas week on it. It is due to a compiler option, but that option was never changed or added by Apple. What did change was Homebrew, I have the local libraries from before this error started (I think prior to HB 2.2) and it works fine with the latest Master. Even if you upgrade HB, it works, what no longer works is installing HB from scratch. It has nothing to do with prerequisites, I removed all of them and reinstalled then using and older HB and it works. Its ONLY when HB is installed.

I have removed the entire local directory and rebuilt from scratch at least 50 times on 10.15,14,13. I wanted to be able to provide more info but I am at a loss. The only thing that allows make to proceed it to remove the FS code, or adding the compiler option like:
"CFLAGS=\"-Wno-unused-function\" ./configure"

This needs to be fixed somehow but after many weeks of work I have no idea how/why this can be fixed. If the FS code is not used why not just removed it?

**Comment by crienzo** [comment] 2020-08-12 13:35
@mjerris is this still an issue in mac?

**Comment by MarioG-X** [comment] 2020-08-12 17:47
It was a couple of weeks ago. I will test multiple versions today and report back. I worked on this for over 5 months, nasty issue.

**Comment by mjerris** [comment] 2020-08-12 17:47
this is fixed in latest master/release

https://github.com/signalwire/freeswitch/commit/546bebbe5e7936a834f5be28ade91808f548215b

**Closed by mjerris** 2020-08-12 17:47 UTC

**Comment by MarioG-X** [comment] 2020-08-12 20:45
I tested release and development in 10.15/14/13 and all is well now. THANK YOU. I still have no idea what is the world changed in homebrew to turn this compiler option on, but at least I will stop working on it. I will update the wiki but the option has no negative effect so no rush.

**Comment by mjerris** [comment] 2020-08-13 14:28
I don't think you need the option now.  I put fixes in the code that should keep it from happening.

**Comment by yangchongduo** [comment] 2020-12-21 07:52
> this is fixed in latest master/release
> 
> [546bebb](https://github.com/signalwire/freeswitch/commit/546bebbe5e7936a834f5be28ade91808f548215b)

Are you sure it's fixed? There are still problems
