### ISSUE TITLE
Voice Quality Issues

### ISSUE THREAD

**Issue by pacomms** [signalwire/freeswitch#949] opened 2020-11-11 16:21 UTC
On new systms we setup (using fusionpbx and fs 1.10.5) we are having what sounds like bad jitter on some calls, we use yealink handsets T53W mainly and we have this issue on all new installs.

We are getting this on all new install using yealink phones, tried multiple firmware

Package version is 1.10.5 on debian 10

Other people on fusionpbx forum have also had this issue, all the machines are VM's running in IONOS datacentre.

**Comment by KrisD888** [comment] 2020-11-16 21:41
I tried moving to both August Releases and recently downloaded Master on November 6th and all have had garbling problems. I immediately started getting user complaints and it seems to be mostly in the conferences that they complain about. It may be worse in one conference and sound OK in another or the garbling may go away for a bit and come back. An "underwater" sounding problem is also reported. It's not an overloaded CPU either. I run DELL R720 Windows 2019 bare metal 20 cores and the CPU usage is at about 10% with 150 sessions.
Every time I have had to go back to a June 28th download of Master (1.10.2) and the garbling problem goes away.

**Comment by snaptel** [comment] 2020-11-17 00:59
You mention that it worked on 1.10.2 download on Jun/28/20, I think 1.10.3 was released in May, so not sure.
Did you try to narrow down which commit is causing this issue? if you do that it might be easier to find the cause of the problem.
https://freeswitch.org/confluence/display/FREESWITCH/Tips+for+using+Git#TipsForUsingGit-GitBisect-TrackingDownBreaksandBugsExtremelyRapidlyWithgit

**Comment by KrisD888** [comment] 2020-11-17 03:21
version command shows 1.10.2. I double checked that I downloaded it on 6/28 and I have the uncompiled code in a zip file so I didn't accidentally recompile it on 6/28. The only thing I can think of is that I did the git clone from the old /stash/ and not from github, so I may have grabbed an older version. I will have to get the May .3 version and see if that works well. I lately use
git clone https://github.com/signalwire/freeswitch.git E:\FS_GIT which I believe gets me the Master. I don't know which commits that has.
I just did bash git clone –b v1.10.3 https://github.com/signalwire/freeswitch.git E:\FS_GIT_1.10.3
I will compile it and report how it goes. Maybe we can narrow down the problem..

**Comment by snaptel** [comment] 2020-11-17 03:30
Do the Git Bisect if possible to find the exact version
or at least test releases 1.10.3 1.10.4 & 1.10.5

**Comment by pacomms** [comment] 2020-11-18 15:55
This seems top be more something to do with Debian 10 in my case I think , I don't get underwater speech sounds its almost like the sounds are clipping.

**Comment by mariogasparoni** [comment] 2020-11-18 16:31
@pacomms , i am also getting something similar to this. In my scenario, i am using mod_conference to handle multiple WebRTC users.

Without mod_conference (for example, a simple webrtc echo call) i am not able to hear it clipping (i have seen a few people calling it 'cracking'). I am also using the conference profile **cdquality**.

I recently started digging into this and my current suspicious points to a mod_conference issue, once i have tested multiple settings and codecs and the result is the basically the same (audio clipping).  Setting both **comfort-noise** and **energy** seems to make audio quality a bit better, but i am still able to hear it clipping

**Comment by pacomms** [comment] 2020-11-20 09:53
This happens to me in general standard calls not conf calls although i wonder if its related. I originally thought it may be the vm as its run on vmware and i know there can be timing issues but non of our other 100+ installs on deb 9 have this issue ..

**Comment by snaptel** [comment] 2020-11-20 16:08
> 
> 
> This happens to me in general standard calls not conf calls although i wonder if its related. I originally thought it may be the vm as its run on vmware and i know there can be timing issues but non of our other 100+ installs on deb 9 have this issue ..

does it work fine on the debian 9 even on the latest 1.10 release?

**Comment by KrisD888** [comment] 2020-11-20 20:02
I am using Windows2019. After compiling and testing in the past few days, here are my results.
I have garbling/stuttering in the conferences, that may come and go, with versions 1.10.2, .3, .5 and a .6 Master downloaded on Nov 6th. .4 must have been very buggy for .5 to be released just 2 weeks later so I didn't bother with it. Playing a file in the conference to a member also garbles. A conference could be garbled, you press # to jump to the next and that one could be clear.
I tried jitterbuffer, plc- nothing helped in the conferences. Using jitterbuffer during bridge seems to help when bridging from one FS box to another. I had a problem with that too when I bridged to another server, the audio started to garble.
 Session.Execute("export", "rtp_jitter_buffer_during_bridge=true");
 Session.Execute("export", "nolocal:jitterbuffer_msec=" + BridgeJitterBuffer);
{execute_on_originate=cng_plc}

I am now running on 1.10.1 and the conferences are fine just like that .2 Master I somehow must have pulled from /stash/
If you try the .1 release and it fixes your audio, then we'll have a confirmation of the issue with the later versions.
It's hard to believe that this can exist a year later, but sometimes people put up with garbling because it could be attributed to lousy internet-hard to identify.

It appears that some change(timing,syncing,threading) between .1 and the .2 Release is screwing up the audio. 

I am putting up a $500 BOUNTY for the Freeswitch team to take a look at this and hopefully get it fixed for the next release.

**Comment by pacomms** [comment] 2020-11-21 09:39
I can confirm i did not have this issue with the 1.10.1 packages. i don't install from source but use packages , is there anywhere i can downoad the 1.10.1 packages from now ?
I am surprised this has crept in and no one else had noticed it, the speech is definitely clipping in conferences and also calls as well.

**Comment by pacomms** [comment] 2020-11-21 09:40
> > This happens to me in general standard calls not conf calls although i wonder if its related. I originally thought it may be the vm as its run on vmware and i know there can be timing issues but non of our other 100+ installs on deb 9 have this issue ..
> 
> does it work fine on the debian 9 even on the latest 1.10 release?

Seems to be ok on deb 9 so far ...

**Comment by pacomms** [comment] 2020-12-06 21:40
No word from the guys at freeswitch regarding this issue ?

**Comment by dancaescu** [comment] 2020-12-09 15:52
This issue is confirmed on 1.10.5 on Debian 10.  We are having garbled audio in calls and sometimes echo. Downgrading to 1.10.3 fixes the issue.

This is the specific version we are having trouble with:

UP 0 years, 9 days, 1 hour, 44 minutes, 24 seconds, 306 milliseconds, 571 microseconds
FreeSWITCH (Version 1.10.5 -release-17-25569c1631 64bit) is ready
31555 session(s) since startup
11 session(s) - peak 42, last 5min 16 
0 session(s) per Sec out of max 100, peak 9, last 5min 3 
1000 session(s) max
min idle cpu 0.00/85.93
Current Stack Size/Max 240K/8192K

Downgrading to  1.10.3 -release-15-129de34d84 (that's whatever we had last) , fixes the issue.

**Comment by dragos-oancea** [comment] 2020-12-09 16:13
do you use a jitterbuffer ? you should.

**Comment by snaptel** [comment] 2020-12-09 16:19
the biggest changes between 1.10.3 & 1.10.5 are the changes of using external build/packages for sofia-sip and spandsp, there is a chance that one of those 2 libs you use (not sure if you built from source or use package) is whats causing the issue, if someone can do a Git Bisect to pinpoint exactly where it breaks (there are 84 commits between 1.10.3 and 1.10.5), even just testing 1.10.4 would narrow the issue a bit.

**Comment by dancaescu** [comment] 2020-12-09 16:24
@dragos-oancea - yes, i do. jitter-buffer has nothing to do with the issue at hand. The exact same config (with jb) works fine on 1.10.3 .

@snaptel - this was installed using apt from the official freeswitch repo , on Debian 10 (Buster). Also, we had several servers running on 1.10.4 , I do not remember seeing any quality complaints.

**Comment by dancaescu** [comment] 2020-12-09 16:27
@snaptel - I have upgraded to 1.10.4 (this is the last version I was at before 1.10.5 upgrade, so I still had the apt packages around).

FreeSWITCH (Version 1.10.4 -release-16-133fc2c870 64bit) is ready

I will provide feedback in 24-48 hours (or as soon as i receive new complaints for audio quality)

**Comment by snaptel** [comment] 2020-12-09 16:38
There are only 22 commits between 1.10.4 and 1.10.5, if indeed 1.10.4 is good then it shouldn't take too long to find the exact commit that breaks it. I personally didn't see this problem in my testing of 1.10.5 but I didn't test for very long and I'm also not using packages (no idea if that makes a difference here)
https://github.com/signalwire/freeswitch/compare/v1.10.4...v1.10.5

**Comment by dancaescu** [comment] 2020-12-09 16:44
The issue does not show up on very low call volumes. All is good at 4-5 simultaneous calls, so this is not noticeable while testing. Nevertheless, whenever i upgraded a server to 1.10.5, as soon as it hits peak times, audio degrades. As mentioned, the exact same servers, on 1.10.3 (or 1.10.4) did not have any issue with the exact volume of calls (or with even higher calls, since 1.10.3 got us through the last holiday season).

What was the call volume you were testing 1.10.5 with?

**Comment by dragos-oancea** [comment] 2020-12-09 17:00
please upload pcap file with the problem.

**Comment by dancaescu** [comment] 2020-12-09 17:15
I am not on 1.10.5 , i downgraded to 1.10.4 and I intend to stay on it for several more days to gather some feedback (see my conversation with snaptel, above) 

Also, PCAP would contain signaling, which is still the same between 1.10.3(1.10.4) and 1.10.5 , and not the RTP, so I am unsure how that could be useful.

**Comment by dragos-oancea** [comment] 2020-12-09 17:45
we need pcap with RTP to figure out if this issue is related with this one: https://github.com/signalwire/freeswitch/issues/963 . 

if so, use https://freeswitch.org/confluence/display/FREESWITCH/send_silence_when_idle and JB to mitigate.

**Comment by dancaescu** [comment] 2020-12-09 18:41
I have emailed you directly and attached PCAPs.

**Comment by dancaescu** [comment] 2020-12-09 19:09
well, it looks like 1.10.4 is also having issues. i will collect some more pcaps and send them over

**Comment by dragos-oancea** [comment] 2020-12-10 09:57
> well, it looks like 1.10.4 is also having issues. i will collect some more pcaps and send them over

there is no RTP in the pcap you sent, only SIP.  however, it seems unrelated with https://github.com/signalwire/freeswitch/issues/963 since I don't see Opus in SDP .

**Comment by pacomms** [comment] 2020-12-14 16:17
I can confirm 1.10.3 doesnt have the issue for me, 1.10.4 & 5 do, clipping speech, poor quality calls espcially when busy.

**Comment by KrisD888** [comment] 2020-12-15 19:42
I compiled a clean Master download yesterday on 12/14/2020 (1.10.6 64bit) on Windows2019. I put my calls into it for conferences and they were garbled- callers, files playing- everything. I had to switch immediately to my old version that works(Master 1.10.2-thats something before the .2 release) The problem I now have with the old is that Verto no longer works with the last Chrome update to version 87 about a week ago. Probably TLS1.2 issue. Chrome 86 works with the old. 87 works on the latest Master. 

!!!   $500 Bounty !!!
I will repeat the bounty I mentioned above- $ 500 for the Freeswitch team 
to look into these audio problems in the conferencing. Let me know when the fix is in the Master and I will test it.

**Comment by snaptel** [comment] 2020-12-15 20:01
> I can confirm 1.10.3 doesn't have the issue for me, 1.10.4 & 5 do, clipping speech, poor quality calls especially when busy.
> 
We're getting closer, I believe that if we pinpoint the exact commit that broke it will make easier for the core team to find and address the issue, there is 62 commits between 1.10.3 and 1.10.4, if someone can do a git bisect it would probably help. I suspect that the issue was introduced in one of the commits of Aug/03 or Aug/04 when sofia & spandsp were moved out of tree, but only testing would confirm.
I would have done it myself but I can't seem to reproduce the issue on my systems.
https://github.com/signalwire/freeswitch/compare/v1.10.3...v1.10.4

**Comment by KrisD888** [comment] 2020-12-21 19:38
Conference audio stutter on Master solved!
In the conference.conf.xml profile I changed the rate from 16000 to 8000 and the interval from 20 to 80. 
      
      <param name="rate" value="8000"/>
      
      <param name="interval" value="80"/>
Here is how to INCREASE the stutter-set the rate to 48000 and interval to 10.  Playing a file to the member will almost always stutter. 
I am guessing here, but it seems something has changed in FS in the past year that is slowing the transcoding and the feeding of data. Windows may be a bit slower in thread switching than Linux too.
Interval 20 is in some other conf files and maybe you need to increase it to solve problems elsewhere. Other than in the conferences, I didn't notice any audio problems.

**Comment by mariogasparoni** [comment] 2020-12-21 19:47
Glad these changes fixed the problem for you @KrisD888.
Do you have any recorded audio so i can compare if the problem you have is the same as ours ? 

The problem we are having is very similar to the clicks at 0:37, 0:44 and 0:48 on this video:
https://www.youtube.com/watch?v=NdqxxZpqF6s

**Comment by KrisD888** [comment] 2020-12-21 19:56
I don't do video. It would garble audio so bad it would be unintelligible and unusable.
Check the energy-level. Maybe you need to reduce it so it's more sensitive. 
"energy-level" value="100"

**Comment by snaptel** [comment] 2020-12-21 20:05
> Conference audio stutter on Master solved!
> In the conference.conf.xml profile I changed the rate from 16000 to 8000 and the interval from 20 to 80.

Problem is not solved you just avoid the problem, and it may come back when you increase load a bit more. I wish someone can nail down the exact commit that caused the issue. as explained I wasn't able to reproduce the issue.

**Comment by mariogasparoni** [comment] 2020-12-21 20:07
@KrisD888 Thanks.
We also don't do video, but i used that YouTube-video once the **audio** problem is very similar.

**Comment by KrisD888** [comment] 2020-12-21 20:38
snaptel, you are probably right that I may be just avoiding the problem but at least it's working for now.  I still think there has been a slowdown in FS feeding data within the 20ms frames. I am guessing it happened about a year ago after 1.10.1.

**Comment by dancaescu** [comment] 2020-12-21 20:51
@snaptel , if you have the .deb packages for the affected versions, I can try them. I was able to consistently reproduce the issue.

Unfortunately, i do not have the debs and the only versions i see in apt is 1.10.5 

root@sbc-ca-01:~# apt-cache madison freeswitch
freeswitch | 1.10.5~release~17~25569c1631~buster-1~buster+1 | http://files.freeswitch.org/repo/deb/debian-release buster/main amd64 Packages
freeswitch | 1.10.5~release~17~25569c1631~buster-1~buster+1 | http://files.freeswitch.org/repo/deb/debian-release buster/main Sources
root@sbc-ca-01:~#

**Comment by tculjaga** [comment] 2021-02-26 07:57
> > I can confirm 1.10.3 doesn't have the issue for me, 1.10.4 & 5 do, clipping speech, poor quality calls especially when busy.
> 
> We're getting closer, I believe that if we pinpoint the exact commit that broke it will make easier for the core team to find and address the issue, there is 62 commits between 1.10.3 and 1.10.4, if someone can do a git bisect it would probably help. I suspect that the issue was introduced in one of the commits of Aug/03 or Aug/04 when sofia & spandsp were moved out of tree, but only testing would confirm.
> I would have done it myself but I can't seem to reproduce the issue on my systems.
> [v1.10.3...v1.10.4](https://github.com/signalwire/freeswitch/compare/v1.10.3...v1.10.4)

@snaptel did you get any chance to pinpoint the root cause of this problem ? I run FS on CentOS/RHEL 8 and ya, 10.1.5 got voice quality issues for bridged calls when the system get a lil more busy.

client1<> PSTN <SIP trunk> FreeSWITCH <webrtc/verto> client2 (chrome/firefox)

FS is controlled by an application via ESL. The application 1st originates a legs to client 1 and 2 and when ready it bridges the two legs using uuid_bridge.

As reported by others, the recording of the call is perfectly fine but both client1 and client2 experience quality issue (client1 and client2 audio out of sync and garbled)

On the SIP trunk leg i see client1 (client1 => FS) RTP is clear having the correct sequence and timestamp but it has a slight packet loss (1-3%) ... meaning RTP packet never arrives.
In the opposite direction (FS => client1) i see all sort of issues... wrong timestamp sudden mark bit set, 

![image](https://user-images.githubusercontent.com/6218342/109271636-1a3dce00-7810-11eb-893b-ae0c6a7f7eae.png)

![image](https://user-images.githubusercontent.com/6218342/109271931-799bde00-7810-11eb-9522-ac69cc6eb01c.png)


So to test my options are as follows:

```dnf --showduplicates list freeswitch
Last metadata expiration check: 1:14:41 ago on Fri 26 Feb 2021 07:06:53 AM CET.
Installed Packages
freeswitch.x86_64                1:1.10.5-2.el8     @okay
Available Packages
freeswitch.x86_64                1.10.1-5.el8
freeswitch.x86_64                1.10.1-6.el8
freeswitch.x86_64                1.10.2-1.el8
freeswitch.x86_64                1.10.2-2.el8
freeswitch.x86_64                1:1.10.2-3.el8
freeswitch.x86_64                1:1.10.2-4.el8
freeswitch.x86_64                1:1.10.3-1.el8
freeswitch.x86_64                1:1.10.4-1.el8
freeswitch.x86_64                1:1.10.5-1.el8
freeswitch.x86_64                1:1.10.5-2.el8
```
let me know what versions to test.

@dragos-oancea i can provide you with pcaps containing RTP packets of both SIP and WebRTC leg

**Comment by dragos-oancea** [comment] 2021-02-26 08:26
please do. Also try to reset the head of spandsp to commit https://github.com/freeswitch/spandsp/commit/04363b1b15961389b670d6fff0a4553ba5e55734 and rebuild everything, and see if you can reproduce (just to eliminate the possibility that an obscured bug went in spandsp)

**Comment by tculjaga** [comment] 2021-02-26 12:15
@dragos-oancea 

the pcap is like 12 MB large, where can i send it ?

**Comment by dragos-oancea** [comment] 2021-02-26 12:30
you can email it to: dragos@freeswitch.org . people that don't want to show IPs in pcap (and upload pcaps to github) can use this:
tcprewrite --dstipmap=X.X.X.X/32:192.168.0.1/32 --srcipmap=X.X.X.X/32:192.168.0.2/32 -i in.pcap -o out.pcap
Tcprewrite is part of Tcpreplay package.
Of course, the IP shows in SIP,  but there are cases when we need only RTP.

**Comment by tculjaga** [comment] 2021-02-26 17:38
@dragos-oancea 

one quick hint:

tshark -s0 -i eth0 -t u "udp[9] = 0x88 && length < 250"

This will capture only RTP with rtp.marker = true.

You can use this to detect problematic streams on your platform while testing bridged calls. The rtp.marker should not be set in mid conversation when you do nothing with the stream e.g. hold/unhold.

**Comment by tculjaga** [comment] 2021-02-26 18:55
update:

this is definitely related to slight packet loss i got on SIP trunk transport link... as when i got a packet missing i observer FS "restarting" the RTP stream from a random timestamp.

**Comment by tculjaga** [comment] 2021-03-10 10:13
Hello everyone,

I used FS ver 1.10.5 compiled from git: ```FreeSWITCH Version 1.10.5-release+git~20200818T185121Z~25569c1631~64bit (git 25569c1 2020-08-18 18:51:21Z 64bit)```

so the conclusion is that voice quality issues experienced (at least in my case) were related to packet loss on core side of Freeswitch (upstream SIP trunk) that translated into huge audio delay and/or part of conversation drop out on bridged calls where interlocutor voice got more and more out of sync with conversation time.

the setup:
```Client1<PSTN> Telekom <SIP Trunk> FreeSWITCH <Verto> Client2```

I can explain exactly what happened but I cannot pinpoint the exact part of the code causing this issue.

As mentioned before, on Client1 leg I get like 1-4% packet loss happening randomly. On both legs we are using PCMA codec.
When we get packet loss on Client1 leg FreeSWITCH for some unknown reason is resetting the RTP stream sent to Client2... setting the marker bit and a **new timestamp**!!!

RTP on Client1 leg
![image](https://user-images.githubusercontent.com/6218342/110610642-b8c21b80-818e-11eb-9451-81915abac26f.png)


RTP on Client2 leg
![image](https://user-images.githubusercontent.com/6218342/110610286-5ff28300-818e-11eb-882b-28173313e349.png)

Timestamp on the RTP packet is curtail for correct audio playback and a sudden swing in deltas just destroys the voice quality. 

With help of  @dragos-oancea I have added some debugging into the code in several places and confirmed the RTP stream is resetting (at least timestamp on the RTP stream). It's strange SSRC was never resetting and that was kind of odd to me.

also @dragos-oancea suggested to activate jitterbuffer on both Client1 and Client2 side but nothing was working since FreeSWITCH is resetting the RTP packet timestamp ... no jitter buffer can coop with that :(

At the end, dragos suggested to move Client2 leg to OPUS (narrowband) and this is where things got better. The issue was still happening but not that often. 

In the mean time networking fixed packet loss and the issue cannot be reproduced anymore... but it is **NOT gone**!
It still remains and if we don't fix it, it will bite us back.

So the bottom line: when we get a slight packet loss on one end FreeSWITCH is violently resetting the RTP timestamp on the other end causing audio delay and jitterbuffer dropouts.

I have sent PCAPs and logs to FS team. I hope they can look into this issue and pinpoint the exact cause of the issue.

@dragos-oancea Thanks for your help!

Regards,
Tihomir.

**Comment by greenbea** [comment] 2021-03-11 20:31
@tculjaga I've seen these incorrect timestamps on my PCAP's for the longest time for over a year I'm currently on 1.10.3

**Comment by snaptel** [comment] 2021-03-18 22:55
While I can't reproduce this issue, I'm still concerned about it so I would offer a Bounty of $200 for this issue to be addressed, this in addition to the $500 Bounty that was offered by @KrisD888. if interested please confirm with me.

**Comment by KrisD888** [comment] 2021-03-19 05:24
I am in with my original $500, if any of these audio issues are looked at. 
My work around for the chatrooms seems to be working for now.

----- Original Message -----

**Comment by dancaescu** [comment] 2021-04-15 11:58
I'll add another $300 to this bounty.

**Comment by dragos-oancea** [comment] 2021-04-15 14:40
please try current master. commit 7fc5d9a7c36337b15a5c7044bdaecdc82d95d94b *might* fix it.

**Comment by snaptel** [comment] 2021-04-15 19:39
@KrisD888 are you testing the commit from @dragos-oancea  ?

**Comment by tculjaga** [comment] 2021-04-15 21:14
hi,

@Dragos Oancea ***@***.***>  do we have centos 8 rpms somewhere ?

**Comment by KrisD888** [comment] 2021-04-16 00:52
I am currently on the last release 1.10.6 with my work-around config 
changes.  Compiled it myself. Seems to work fine. I am on Windows 2019.

Kris

----- Original Message -----

**Comment by snaptel** [comment] 2021-04-16 00:56
@KrisD888  would you mind compiling latest master and test without your work-around config changes so that we know if it's fixed or not?

**Comment by dragos-oancea** [comment] 2021-04-19 13:58
> hi, @dragos-oancea do we have centos 8 rpms somewhere ?

Andrey told me we only have rpms for Centos 7, not 8

**Comment by KrisD888** [comment] 2021-04-20 01:03
snaptel,

I just did the Release a few days ago so it can't be that different than the 
Master. I am working remotely and I don't want to mess with it for a while. 
It takes up my whole day and irritates my conference users if it it's 
stuttering. I will give it a few months before I try the Master again and I 
kind of want to know that the Freswitch team has worked on it before I try 
the old config settings.


----- Original Message -----

**Comment by snaptel** [comment] 2021-04-20 02:26
@KrisD888 seems like you missed the message from @dragos-oancea he pushed out a potential fix after the release, so you would have to test master to have that fix.

**Comment by SynaptiQ-Code** [comment] 2021-04-27 12:44
I think that I am also experiencing the issue reported here.

Experiencing issues with audio 'clipping' and 'cracking' and just generally dropping out for users whilst running FreeSWITCH 1.10.5-release-17-25569c1631~64bit on Debian 10.

I can't replicate this when doing testing in our quiet hours, but when things busy up we definitely get reports of call quality issues affecting a number of different users where some of them have perfectly capable internet and hardware.

It could indeed be slight packet loss kicking off the issues as we do sometimes have networking issues at the DC side or at the users side to begin with, but it's certainly a bigger issue than this.

I do seem to recall being completely unable to see any fault like this when initially testing FS on Deb10 with the 1.10.x series so it very well could be something introduced in 1.10.4 that is causing our users issues.

> please try current master. commit [7fc5d9a](https://github.com/signalwire/freeswitch/commit/7fc5d9a7c36337b15a5c7044bdaecdc82d95d94b) _might_ fix it.

I'll give this a try and report back if this improves things for my users.

It should be possible to get feedback from them on this relatively quickly.

**Comment by MuramotoAkira** [comment] 2021-04-27 12:44
I think that I am also experiencing the issue reported here.

Experiencing issues with audio 'clipping' and 'cracking' and just generally dropping out for users whilst running FreeSWITCH 1.10.5-release-17-25569c1631~64bit on Debian 10.

I can't replicate this when doing testing in our quiet hours, but when things busy up we definitely get reports of call quality issues affecting a number of different users where some of them have perfectly capable internet and hardware.

It could indeed be slight packet loss kicking off the issues as we do sometimes have networking issues at the DC side or at the users side to begin with, but it's certainly a bigger issue than this.

I do seem to recall being completely unable to see any fault like this when initially testing FS on Deb10 with the 1.10.x series so it very well could be something introduced in 1.10.4 that is causing our users issues.

> please try current master. commit [7fc5d9a](https://github.com/signalwire/freeswitch/commit/7fc5d9a7c36337b15a5c7044bdaecdc82d95d94b) _might_ fix it.

I'll give this a try and report back if this improves things for my users.

It should be possible to get feedback from them on this relatively quickly.

**Comment by MuramotoAkira** [comment] 2021-04-27 12:44
I think that I am also experiencing the issue reported here.

Experiencing issues with audio 'clipping' and 'cracking' and just generally dropping out for users whilst running FreeSWITCH 1.10.5-release-17-25569c1631~64bit on Debian 10.

I can't replicate this when doing testing in our quiet hours, but when things busy up we definitely get reports of call quality issues affecting a number of different users where some of them have perfectly capable internet and hardware.

It could indeed be slight packet loss kicking off the issues as we do sometimes have networking issues at the DC side or at the users side to begin with, but it's certainly a bigger issue than this.

I do seem to recall being completely unable to see any fault like this when initially testing FS on Deb10 with the 1.10.x series so it very well could be something introduced in 1.10.4 that is causing our users issues.

> please try current master. commit [7fc5d9a](https://github.com/signalwire/freeswitch/commit/7fc5d9a7c36337b15a5c7044bdaecdc82d95d94b) _might_ fix it.

I'll give this a try and report back if this improves things for my users.

It should be possible to get feedback from them on this relatively quickly.

**Comment by MarioG-X** [comment] 2021-05-02 20:45
I retested #963 this weekend and made sure everything was exactly the same with the same problem voicemail recording it played back perfectly! Seems like it's finally fixed, keep in mind this is on a test machine with no volume, but this recording was unintelligible before. Huge improved difference.

**Comment by MuramotoAkira** [comment] 2021-05-04 00:09
This is still looking good to me.

Can confirm that #949 and #963 are resolved, having built master on deecaae.

I would vote to add these fixes to the 1.10.7 release and get that out as soon as practicable.

**Comment by snaptel** [comment] 2021-05-04 01:18
@dragos-oancea I would like to pay my part of the bounty, please let me where to send it.

**Comment by dragos-oancea** [comment] 2021-05-04 09:58
> @dragos-oancea I would like to pay my part of the bounty, please let me where to send it.

We cannot accept bribes. Err, bounties :)

On a more serious note FreeSwitch maintenance and development is already paid for by SignalWire.

**Comment by tculjaga** [comment] 2021-05-04 11:57
Hi,
@dragos-oancea  I'm going to be available somewhere next week for few days to setup a lab with artificially introduced packet loss and jitter. I will test 1.10.5 against whatever release you suggest.

What version should contain the fix ?
Was the fix backported to lower versions ?

need to know this in order to setup the lab properly.

Thanks!
Tihomir

**Comment by dragos-oancea** [comment] 2021-05-04 12:21
@tculjaga ,  test 1.10.6 against current FS master.

**Comment by snaptel** [comment] 2021-05-04 13:20
> 
> 
> > @dragos-oancea I would like to pay my part of the bounty, please let me where to send it.
> 
> We cannot accept bribes. Err, bounties :)
> 
> On a more serious note FreeSwitch maintenance and development is already paid for by SignalWire.

So what should I do with the $200 bounty i promised?

**Comment by dragos-oancea** [comment] 2021-05-13 09:30
No backporting planned, please use FS master. Or cherry-pick the patch in your version. Closing.

**Closed** 2021-05-13 09:32 UTC
Labels: bug
