### ISSUE TITLE
lua.conf.xml script_directory parameter not working

### ISSUE THREAD

**Issue by r-duran** [signalwire/freeswitch#1483] opened 2021-12-14 06:01 UTC
**Describe the bug**
I set `<param name="script-directory" value="/etc/freeswitch/scripts/?.lua"/>` in lua.conf.xml and restart freeswitch. But I can't use scripts in "/etc/freeswitch/scripts/" directory as expected.

**To Reproduce**
1. Add "`<param name="script-directory" value="/etc/freeswitch/scripts/?.lua"/>`" in lua.conf.xml and restart freeswitch.
2. Look at logs and you see "[INFO] mod_lua.cpp:337 lua: appending script directory: '/etc/freeswitch/scripts/?.lua'" so the parameter is working
3. Create a test script "test.lua" in "/etc/freeswitch/scripts/"
4. In fs_cli run "lua test.lua"
5. You get error "[ERR] mod_lua.cpp:202 cannot open /usr/share/freeswitch/scripts/test.lua: No such file or directory"
6. run "global_getvar script_dir" in fs_cli, you see only "/usr/share/freeswitch/scripts", so it seems lua.conf script-directory clould not add the directory path we added.

**Expected behavior**
"script-directory" parameter in lua.conf.xml should work as expected and we should use the new directory for lua scripts.

**Package version or git hash**
 - Debian Bullseye Version [1.10.7~release~19~883d2cb662~bullseye-1~bullseye+1]

**Trace logs**

**backtrace from core file**

**Comment by seven1240** [comment] 2021-12-14 13:08
script directory is search path of lua modules not files, use `freeswitch -scripts path` to change it, see help

```
	-scripts [scriptsdir]   -- alternate directory for scripts
```

**Comment by andywolk** [comment] 2021-12-22 14:27
Let's close this as not a bug. Unless there is something new comes in the future.

**Closed by andywolk** 2021-12-22 14:27 UTC
Labels: bug
