### ISSUE TITLE
sip.js websocket terminated by Freeswitch

### ISSUE THREAD

**Issue by Gumunryong** [signalwire/freeswitch#1041] opened 2021-01-22 16:10 UTC
Hi everyone,

we are currently running a custom-build phone application using sip.js which registers to the websocket of our Freeswitch. Our Freeswitch uses version 1.10.3 64 bit on a Debian buster. 

We started to notice the following:
In a set out of ~4000 successful calls we have about 80 calls where during call initiation the websocket is closed by the freeswitch. Which forces the sip.js library to re-register to the websocket. After this occurence there is somehow still rtp coming from the phone application but not from the freeswitch to the phone application. The call is timed-out after 30seconds. 

The sip.js library logs the following to chrome console:
Fri Jan 22 2021 16:34:57 GMT+0100 (Mitteleuropäische Normalzeit) | sip.transport | WebSocket closed without SIP.js requesting it

I increased the loglevel to 9 in console and managed to capture this:

`tport.c:2784 tport_wakeup() tport_wakeup(0x7fdc9439e440): events IN
tport.c:2882 tport_recv_event() tport_recv_event(0x7fdc9439e440)
tport.c:2165 tport_shutdown0() tport_shutdown0(0x7fdc9439e440, 2)
tport.c:2098 tport_close() tport_close(0x7fdc9439e440): wss/10.128.130.129:56027/sips
nua_registrar.c:203 registrar_tport_error() tport error 0: Success
tport.c:4240 tport_release() tport_release(0x7fdc9439e440): (nil) by 0x7fdc941e0f90 with (nil)
nua_stack.c:271 nua_stack_event() nua(0x7fdc941e0f90): event i_media_error 500 Transport error detected
tport.c:4240 tport_release() tport_release(0x7fdc9439e440): 0x7fdc94148b40 by 0x7fdc94060310 with (nil)
nua_stack.c:359 nua_application_event() nua: nua_application_event: entering
tport.c:2792 tport_wakeup() tport_wakeup(0x7fdc9439e440): tport is closed! Setting secondary timer!`

Anybody else ran into this issue and might know what causes it? 

Kind Regards,

**Comment by pcastrejon** [comment] 2021-02-18 16:47
Hi, 
same issue for me, running FS 1.10.5-release-17-25569c1631~64bit on Debian buster.

Im connecting through secure websocket on port 7443, client is also an Angular + SIPJS, using letsecncrypt certs and FS is connected to Twilio account to handle both incoming and outgoing calls.

The issue seems to be random but when it happens, it is always when I click the 'Answer' button and in that moment, the websocket is closed.

Prior to the Agent registration, I have the websocket connected at transport level and a ping every 3 seconds as a keepalive for the connection (I have also tried 20 seconds to avoid too much traffic in short periods of time)

Before answering, I have to register my agent so I send the REGISTER command from the webapp and this works just fine, FS is challenging for the auth and finally reigstration is done OK.

For more info, Im running FS in an azure subscription (all IPs and ports are supposedly whitelisted as required) but my clients are connected trhough a VPN, when the call is correctly connected, Im have voice on both sides and Im able to correctly hang up the call so Im discariding a problem with certs because that has to be binary, it works or not.

So any thought or idea on what can be wrong is welcome, Im also getting the  "i_media_error 500 Transport error detected" message in the FS logs:

```
nua_stack.c:271 nua_stack_event() nua(0x7fc960000ca0): event i_state 180 Ringing
nua_stack.c:359 nua_application_event() nua: nua_application_event: entering
tport.c:2311 tport_set_secondary_timer() tport(0x7fc9400d8860): reset timer
nua_stack.c:359 nua_application_event() nua: nua_application_event: entering
nua.c:370 nua_handle_magic() nua: nua_handle_magic: entering
nua.c:370 nua_handle_magic() nua: nua_handle_magic: entering
nua.c:370 nua_handle_magic() nua: nua_handle_magic: entering
2021-02-15 19:19:36.322059 [DEBUG] sofia.c:7326 Channel sofia/internal/l8v2cvs7@mi4q1on56rfc.invalid entering state [proceeding][180]
2021-02-15 19:19:36.322059 [NOTICE] sofia.c:7437 Ring-Ready sofia/internal/l8v2cvs7@mi4q1on56rfc.invalid!
2021-02-15 19:19:36.322059 [DEBUG] switch_channel.c:3437 (sofia/internal/l8v2cvs7@mi4q1on56rfc.invalid) Callstate Change DOWN -> RINGING
nua.c:370 nua_handle_magic() nua: nua_handle_magic: entering
nta.c:1300 agent_timer() nta: timer set next to 3307 ms
tport.c:2795 tport_wakeup() tport_wakeup(0x7fc9400d8860): events IN
tport.c:2893 tport_recv_event() tport_recv_event(0x7fc9400d8860)
tport.c:3234 tport_recv_iovec() tport_recv_iovec(0x7fc9400d8860) msg 0x7fc9400cc0a0 from (wss/10.201.248.5:56356) has 4 bytes, veclen = 1
tport.c:3052 tport_deliver() tport_deliver(0x7fc9400d8860): bad msg 0x7fc9400cc0a0 (0 bytes) from wss/10.201.248.5:56356/sips next=(nil)
tport.c:2311 tport_set_secondary_timer() tport(0x7fc9400d8860): reset timer
tport.c:2795 tport_wakeup() tport_wakeup(0x7fc9400d8860): events IN
tport.c:2893 tport_recv_event() tport_recv_event(0x7fc9400d8860)
tport.c:2165 tport_shutdown0() tport_shutdown0(0x7fc9400d8860, 2)
tport.c:2098 tport_close() tport_close(0x7fc9400d8860): wss/10.201.248.5:56356/sips
tport.c:4251 tport_release() tport_release(0x7fc9400d8860): 0x7fc9400c4420 by 0x7fc9400c79c0 with (nil)
nua_registrar.c:203 registrar_tport_error() tport error 0: Success
tport.c:4251 tport_release() tport_release(0x7fc9400d8860): (nil) by 0x7fc9400cf780 with (nil)
nua_stack.c:271 nua_stack_event() nua(0x7fc9400cf780): event i_media_error 500 Transport error detected
tport.c:4251 tport_release() tport_release(0x7fc9400d8860): 0x7fc9407ec4f0 by 0x7fc9400a3360 with (nil)
nua_stack.c:359 nua_application_event() nua: nua_application_event: entering
tport.c:2803 tport_wakeup() tport_wakeup(0x7fc9400d8860): tport is closed! Setting secondary timer!
```

Thanks in advance

**Comment by yonghuangqz** [comment] 2021-05-04 01:50
same issue with 1.10.5-release+git~20200818T185121Z~25569c1631~64bit.
I'd traced this and found the reason: SSL_read returned SSL_ERROR_SSL.

Can any one fix it?

Thanks a lot

**Comment by tornad** [comment] 2021-05-07 09:40
> We implemented a workaround by moving the websocket to a proxy which terminates it for us and forwards the sip messages to the freeswitch. We could not find the root cause of it. Since we have the proxy in place the calls are no longer terminated.
> 
> Hope this is atleast a little helpful.

Thanks for this return. I quickly tried a similar solution but failed to implement quickly the proxy and make it works.
Can you tell me which proxy have you use for this ?

thx

**Comment by diminou91** [comment] 2021-05-31 09:44
Hi, I have a similar issue as well. I did try out https://www.nginx.com/blog/websocket-nginx/ as a proxy, mentionned by Gumunryong but with no success.
@Gumunryong did you use nginx to mitigate the isssue ? Or something else ?
Thanks in advance! :)

**Comment by martyrs** [comment] 2021-06-28 17:09
Hello,
Same issue here.
```
nua_stack.c:529 nua_signal() nua(0x7f566401c620): sent signal r_handle_unref
nua.c:1181 nua_unref_user() nua: nua_unref_user: entering
nua_stack.c:529 nua_signal() nua((nil)): sent signal r_unref
tport.c:2165 tport_shutdown0() tport_shutdown0(0x7f56640680c0, 2)
tport.c:2098 tport_close() tport_close(0x7f56640680c0): wss/176.91.193.107:33888/sips
nua_registrar.c:203 registrar_tport_error() tport error 0: Success
tport.c:4251 tport_release() tport_release(0x7f56640680c0): (nil) by 0x7f5664052a50 with (nil)
nua_stack.c:271 nua_stack_event() nua(0x7f5664052a50): event i_media_error 500 Transport error detected
nua_registrar.c:203 registrar_tport_error() tport error 0: Success
tport.c:4251 tport_release() tport_release(0x7f56640680c0): (nil) by 0x7f566401c620 with (nil)
nua_stack.c:271 nua_stack_event() nua(0x7f566401c620): event i_media_error 500 Transport error detected
```

**Comment by Gumunryong** [comment] 2021-07-30 09:55
We put a kamailio infront of the freeswitch as proxy. It terminates the websocket on the kamailio and passes through the registration as a regular sip request to the freeswitch. This came as the ideal choice since it can do websocket and speaks SIP at the same time. You can probably do it with any proxy that is capable of editing header fields.    
 Since implementation we had no more issues.

**Comment by szdefine** [comment] 2021-08-18 06:09
we have the same problem here too. 
freeswitch is :1.10.5-release.8~64bit  and jssip is :3.7
how can this bug can be fixed? thanks!

**Comment by yonghuangqz** [comment] 2021-08-21 02:19
in my opnion, openssl library caused this.

**Comment by tornad** [comment] 2021-08-21 08:34
> in my opnion, openssl library caused this.

Yes I agree. When I tried to identify the cause, my test lets me think the problem occurs at the SSL level, not SIP protocol.
the socket is closed from the freeswitch side, but why...

But for me, the bug was introduce between FS 1.10.2 and 1.10.5

We have the bug on different hosts, no problem on FS 1.10.2, only on FS with 1.10.5 or 1.10.6
So we are locked on 1.10.2 for our sipjs/websocket customers.
I also could bet the problem is present on normal SIP SSL TCP connection (no websocket); but SIP SSL TCP is less used so not occurs enough to be catch.

On my FS 1.10.2 (no problem)
FreeSWITCH (Version 1.10.2 -release-14-f7bdd3845a 64bit) is ready
        libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f58d3995000)

On FS with problem
libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007fbf95b66000)
OpenSSL 1.1.1d  10 Sep 2019
FreeSWITCH (Version 1.10.5 -release-17-25569c1631 64bit) is ready
        libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007fe18ecd8000)
OpenSSL 1.1.1d  10 Sep 2019
FreeSWITCH (Version 1.10.5 -release-17-25569c1631 64bit) is ready
        libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f27116c1000)
OpenSSL 1.1.1d  10 Sep 2019
FreeSWITCH (Version 1.10.6 -release-18-1ff9d0a60e 64bit) is ready
        libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f7708059000)

**Comment by Soulsuke** [comment] 2021-09-14 07:22
Thank you both  @Gumunryong  and @tornad .
A client suddenly asked us to develop a software which needed to connect via websocket to their freeswitch 1.10.6 instance, and we couldn't figure out why we started getting all those 1006 errors.

Sadly, the client opted to downgrade to 1.10.2 (from 1.10.6) instead of putting up a websocket proxy...

I wonder if this bug has already been acknowledged though.

**Comment by szdefine** [comment] 2021-09-17 05:09
Thank you both @Gumunryong and @tornad too.
we had to downgrade from 1.10.5 to 1.10.2 for using jssip clients.
hope this bug will be fixed soon .

**Comment by 2954456878** [comment] 2022-02-16 06:53
I have the same problem，Is there a solution？

**Comment by lonelyxmas** [comment] 2022-05-26 09:04
I have the same problem，Is there a solution？

**Comment by jalsot** [comment] 2022-06-14 12:18
I wonder if it is not related to this one: https://github.com/freeswitch/sofia-sip/pull/132
Maybe somebody could try out?

**Comment by jalsot** [comment] 2022-06-14 15:37
The patch in the given PR has not been merged and not released in 1.13.8, so the only way to try out is to apply the patch to sofia-sip git master and recompile it. After that FS restart is needed (maybe reloading mod_sofia module is enough, but not sure).

**Comment by cash168** [comment] 2022-06-17 10:10
I compiled libsofia-sip-ua.so.0.6.0 with a fix. the problem with (code: 1006) is still there.

**Comment by jalsot** [comment] 2022-06-30 09:08
Have you tried 1.10.7 FS version?
Is it possible to reproduce the issues? (we have similar issues but cannot reproduce at will and happens very rarely)

**Comment by balazsradak** [comment] 2022-07-01 14:16
> We put a kamailio infront of the freeswitch as proxy. It terminates the websocket on the kamailio and passes through the registration as a regular sip request to the freeswitch. This came as the ideal choice since it can do websocket and speaks SIP at the same time. You can probably do it with any proxy that is capable of editing header fields. Since implementation we had no more issues.

HI Gumuryong, 
I'm having the same issue and trying to figure out how to use kamailio the way you mention. I managed to get work kamailio with the websocket module, but my problem is that kamailio is also act as a registar server, which is not good for me, since freeswitch should be the registart because I need to use the FS call_center module. If you could share me some kamailo.cfg it would be very helpful! 

Thanks!

**Comment by jalsot** [comment] 2022-08-01 09:29
As far as I understood from the original report and from the additional comments that the issue might be between v1.10.2 and v1.10.3 (last good version and first appearance).
Is here anybody who could consistently reproduce (the best would be at will) the issue and collect more details for debugging?

@Gumunryong possibly could you share your Kamailio config as a workaround please?

**Comment by Grandmeo** [comment] 2022-09-06 08:42
Hello, we have the same issue, using Freeswitch 1.10.6 and sip.js version 0.16.1.
It seems to be linked with network charge, perhaps when the SIP/WSS packets are segmented.
Often on the SIP: 200 OK from the callee which is a big packet, if this packet comes in 2 assembled TCP segments this issue sometimes occurs (not in 100% case).

I add two pcap traces with sip on a-leg and wss (tcp:7443) on WebRTC leg, both have the wss closed at end of trace.
[WebSocketClose20220831-3.zip](https://github.com/signalwire/freeswitch/files/9494914/WebSocketClose20220831-3.zip)
[WebSocketClose20220831-2.zip](https://github.com/signalwire/freeswitch/files/9494915/WebSocketClose20220831-2.zip)

Perhaps we should choose the Nginx or Kamailio for proxying wss... 

Best regards.
Grandméo.

**Comment by jerry6021** [comment] 2022-09-16 20:02
Has there been progress on this issue?

still have it with the latest version.

**Comment by jerry6021** [comment] 2022-09-16 22:26
we are using:
debian 10
FS 1.10.6
libsofia-sip-au 1.13.8
Lets Encrypt
WSS

**Comment by jerry6021** [comment] 2022-09-16 22:27
we get the 1006 error very randomly...
After 3 weeks of trying to get WSS working, there is no noticeable pattern to the failures...

**Comment by jerry6021** [comment] 2022-09-21 17:28
For anyone that wants to follow:

https://github.com/freeswitch/sofia-sip/issues/172

**Comment by andywolk** [comment] 2022-09-22 14:50
Fixed by https://github.com/freeswitch/sofia-sip/pull/175

**Closed by andywolk** 2022-09-22 14:50 UTC

**Comment by ttaoyuan** [comment] 2022-09-23 05:11
good news！
