### ISSUE TITLE
FreeSWITCH segfaults on Debian 10.9

### ISSUE THREAD

**Issue by keesvandenbos** [signalwire/freeswitch#1238] opened 2021-06-18 14:28 UTC
FreeSWITCH crashes with core dump indicating libcrypto. It happens under low load when running around 150 SIP to WebRTC calls. Not reproducible manually, it happens random on multiple boxes.

    Freeswitch Version: 1.10.6-release-18
    Linux kernel version: SMP Debian 4.19.181-1
    OS Distribution: Debian 10.9 

I am not sure it is a generic problem or related to my specific configuration.

If you can provide me some hints or direction, it will be helpful.

Thanks in advance for your attention.

[backtrace.log](https://github.com/signalwire/freeswitch/files/6677594/backtrace.log)

**Comment by dragos-oancea** [comment] 2021-06-18 14:42
try this patch: https://github.com/signalwire/freeswitch/pull/1211

**Comment by keesvandenbos** [comment] 2021-06-18 14:51
I will try it and report back. 

Thank you for the fast response!

**Comment by keesvandenbos** [comment] 2021-06-22 18:38
Freeswitch segfaulted again. I installed a new Debian server and compiled the stable branch 1.10.6-release git 1ff9d0a 2021-03-25 13:16:09Z 64bit with the patch. Syslog shows an error in libcrypto after witch systemd declares Freeswitch dead.

Jun 22 16:00:41 webrtc kernel: [67840.642428] freeswitch[3501]: segfault at 0 ip 00007f877aac7a45 sp 00007f8770bb9908 error 6 in libcrypto.so.1.1[7f877a92a000+19e000]
Jun 22 16:00:42 webrtc systemd[1]: freeswitch_source.service: Main process exited, code=killed, status=11/SEGV
Jun 22 16:00:42 webrtc systemd[1]: freeswitch_source.service: Failed with result 'signal'.

It is a pretty basic installation without any special dial plan or fuctions. Its is SIP in and WebRTC out. 

[backtrace_20210622.log](https://github.com/signalwire/freeswitch/files/6696604/backtrace_20210622.log)

**Comment by dragos-oancea** [comment] 2021-06-24 10:47
the last backtrace is useless. we need debugging symbols. hard to tell it crashes in the same place as before. Also FS debug logs may show useful information.

**Comment by keesvandenbos** [comment] 2021-06-28 13:35
The stable release patched with the above patch, keeps crashing with the same frequency as the stable Debian packages without the patch.  Attached to this message is the backtrace. Below the debug log section at the moment of the crash:

nua_stack.c:569 nua_stack_signal() nua(0x7fdc044a6560): recv signal r_destroy
nta.c:4499 nta_leg_destroy() nta_leg_destroy((nil))
nua_stack.c:569 nua_stack_signal() nua(0x7fdc044a6560): recv signal r_handle_unref
nua_stack.c:569 nua_stack_signal() nua((nil)): recv signal r_unref
f49e7b5e-6805-43a9-a2a4-660fe76bd35f 2021-06-28 14:49:49.394465 [DEBUG] switch_rtp.c:5624 Send start packet for [1] ts=3305755265 dur=160/160/640 seq=19010 lw=3305755265
f49e7b5e-6805-43a9-a2a4-660fe76bd35f 2021-06-28 14:49:49.414463 [DEBUG] switch_rtp.c:5523 Send middle packet for [1] ts=3305755265 dur=320/320/640 seq=19011 lw=3305755425
f49e7b5e-6805-43a9-a2a4-660fe76bd35f 2021-06-28 14:49:49.434463 [DEBUG] switch_rtp.c:5523 Send middle packet for [1] ts=3305755265 dur=480/480/640 seq=19012 lw=3305755585
2021-06-28 14:49:49.434463 [DEBUG] switch_scheduler.c:147 Deleting task 5889 switch_ivr_schedule_hangup (71904449-e78f-4456-be75-a8a4fa87c677)
f49e7b5e-6805-43a9-a2a4-660fe76bd35f 2021-06-28 14:49:49.454473 [DEBUG] switch_rtp.c:5523 Send end packet for [1] ts=3305755265 dur=640/640/640 seq=19013 lw=3305755585
f49e7b5e-6805-43a9-a2a4-660fe76bd35f 2021-06-28 14:49:49.454473 [DEBUG] switch_rtp.c:5523 Send end packet for [1] ts=3305755265 dur=640/640/640 seq=19014 lw=3305755585
f49e7b5e-6805-43a9-a2a4-660fe76bd35f 2021-06-28 14:49:49.454473 [DEBUG] switch_rtp.c:5523 Send end packet for [1] ts=3305755265 dur=640/640/640 seq=19015 lw=3305755585
f49e7b5e-6805-43a9-a2a4-660fe76bd35f 2021-06-28 14:49:49.454473 [DEBUG] switch_rtp.c:5471 Queue digit delay of 40ms
cb11aae3-e071-4ccd-92ca-4041d20ed375 2021-06-28 14:49:49.894624 [INFO] switch_rtp.c:3289 Changing audio DTLS state from HANDSHAKE to SETUP
cb11aae3-e071-4ccd-92ca-4041d20ed375 2021-06-28 14:49:49.914485 [INFO] switch_rtp.c:3196 audio Fingerprint Verified.
cb11aae3-e071-4ccd-92ca-4041d20ed375 2021-06-28 14:49:49.914485 [INFO] switch_rtp.c:4287 Activating audio Secure RTP SEND
2021-06-28 14:49:49.914485 [DEBUG] switch_core_sqldb.c:2836 Secure Type: srtp:dtls:AES_CM_128_HMAC_SHA1_80
cb11aae3-e071-4ccd-92ca-4041d20ed375 2021-06-28 14:49:49.914485 [INFO] switch_rtp.c:4265 Activating audio Secure RTP RECV
cb11aae3-e071-4ccd-92ca-4041d20ed375 2021-06-28 14:49:49.914485 [INFO] switch_rtp.c:3238 Changing audio DTLS state from SETUP to READY
2021-06-28 14:49:49.914485 [DEBUG] switch_core_sqldb.c:2836 Secure Type: srtp:dtls:AES_CM_128_HMAC_SHA1_80
2021-06-28 14:49:51.560162 [CONSOLE] switch_loadable_module.c:1803 Successfully Loaded [mod_logfile]
2021-06-28 14:49:51.560390 [CONSOLE] switch_loadable_module.c:1803 Successfully Loaded [mod_syslog]
2021-06-28 14:49:51.560658 [NOTICE] mod_json_cdr.c:113 Rotating log file paths

[backtrace_23853_20210628_anonymous.log~](https://github.com/signalwire/freeswitch/files/6726630/backtrace_23853_20210628_anonymous.log)

**Comment by andywolk** [comment] 2021-06-28 13:52
Please update to the latest sofia-sip and freeswitch master. Should be fixed. Reopen if the issue is still there.

**Closed by andywolk** 2021-06-28 13:52 UTC
Labels: bug
