### ISSUE TITLE
outbound Calls (leg b) are not getting cleared, even after call gets hang-up 

### ISSUE THREAD

**Issue by andrewudxgen** [signalwire/freeswitch#960] opened 2020-11-30 10:13 UTC
Hello Dear,

we have installed new version of FS - 1.10.5 last day, we have observed, leg b calls are not clearing from FS, though even after calls are hanged-up. we are getting leg b (outbond) CDR through cdr_xml. 

FS console: **show calls** ==> command, shows the calls which been disconnected.

When we try to kill using outbound UUID we are getting Err: **-ERR No such channel!**

could you please help us to fix the same. before we were used, 1.10.1 which was running good.

Thanks in advance

**Comment by w1l50n** [comment] 2020-12-06 00:59
we ran into similar problem, but in our case we don't get the CDR at all. The call channel seems to be just stuck in some wired state and not taking any command (e.g. uuid_kill return No such channel). Try to reproduce the scenario is like tracing ghost, because it doesn't happen to all FS instances we have. For those it end up racking up the zombie channels, it take between 4 - 24 hours with 2-3 outbound call per seconds (it is very unpredictable). 

I try to check out the past issues that may be related, but I can't make anything out of it:
[Kill channel freeswitch not exits #34 ](https://github.com/signalwire/freeswitch/issues/34)
[FS-10252 :- channel zombie not kill #138 ](https://github.com/signalwire/freeswitch/issues/138)
[Zombie calls #178 ](https://github.com/signalwire/freeswitch/issues/178)
[The main-thread reports memory allocation and release errors. #657 ](https://github.com/signalwire/freeswitch/issues/657)

Any suggestion on how to dig into this?

**Comment by ccppprogrammer** [comment] 2020-12-29 07:52
I have the same problem on `FreeSWITCH Version 1.10.3-release-15-129de34d84~64bit (1.10.3 -release-15-129de34d84 64bit)`

**Comment by remdragon** [comment] 2021-01-08 03:00
I have been having this problem for a couple years. It accumulates on average a half dozen ghost calls a month until we restart freeswitch to clear them.

FreeSWITCH Version 1.8.4+git~20181227T011058Z~749a6e108b~64bit (git 749a6e1 2018-12-27 01:10:58Z 64bit)
Debian 9.9

**Comment by mahald** [comment] 2021-02-10 14:21
faceing the same issues seems to occure since 1.10.3. It however for us only happens to a single destination number. outbund_channel does not get cleared, but cdr seems to be written ok.

**Comment by remdragon** [comment] 2021-02-10 14:50
Ran into a new situation yesterday that seems like it could be the same problem as reported in this issue:

* rebooted a CIFS server that was acting up
* autofs on one FreeSWITCH box recovered but on the other ( primary ) it went "pathological"
* attempts to cd into autofs folder hang indefinitely, have to kill bash
* restarting autofs service did not fix the problem ( eventually had to reboot the box )
* put freeswitch in drain mode ( fsctl shutdown asap ), noticed a bunch of outbound calls stuck
* tried to uuid_kill them but uuid_kill says they don't exist
* looking at them more closely, these outbound calls all appeared to be "stuck" in a lua script that was trying to read a file from that autofs mount

I'm wondering if this phantom call problem is a problem that a channel won't get cleared up as long as a lua script still holds a reference to it.
The lua script was being executed via the lua command (it needs to be able to set callerid) so I believe that means it holds an implicit reference to the call.

The file i/o code in lua looks like this:

```
        fd = io.open ( "/mnt/smb/[SNIP]/callerid.txt", "r" )
        if fd then
                cid_number = fd:read()
                cid_name = fd:read()
                fd:close()
                uuid_setvar ( uuid, 'outbound_caller_id_number', cid_number )
                uuid_setvar ( uuid, 'outbound_caller_id_name', cid_name )
                uuid_setvar ( uuid, 'custom_caller_id', cid_number )
                uuid_setvar ( uuid, 'custom_caller_name', cid_name )
        end
```
My guess is that the io.open() hung indefinitely.

**Comment by remdragon** [comment] 2021-02-11 13:59
Different client than either of previous two comments ( I have 3 clients that are all experiencing this bug to some extent ). This client is experiencing this bug in a bad way, accumulating multiple ghost calls per hour. I wrote a lua script that runs once every 5 minutes that deletes any records from the channels and calls tables in core if the uuid/call_uuid doesn't exist, but this morning I got a call that their primary FreeSWITCH was down after it had only been running about a week. I logged in to see that there was one call on the primary FreeSWITCH and that all traffic was going through the backup.

I found this in the logs:

nta.c:6812 incoming_reply() nta: sent 503 Maximum Calls In Progress for INVITE (144876253)

I made a copy of all FreeSWITCH's core db files before restarting the FreeSWITCH service, but looking through them I don't see anything obvious. Skimming through the source code, it seems that in sofia.c there's a session_manager.session_count that might be the problem, but no idea how to reset that without restarting FreeSWITCH or what situation is leading to these sessions not getting cleaned up properly.

This is a Debian 10 box running FreeSWITCH Version 1.10.5-release-17-25569c1631~64bit (-release-17-25569c1631 64bit).

It is a clone of another FreeSWITCH box that is not experiencing this problem.

**Comment by shaunjstokes** [comment] 2021-02-24 13:09
We have this exact same issue when using the originate command with a loopback on 'Debian 10' 'FS 1.10.5'.

**Comment by shaunjstokes** [comment] 2021-02-24 13:33
I've done some debugging, the stuck channels never get past line 1728 `switch_core_session_write_lock(session);`.

**Comment by shaunjstokes** [comment] 2021-02-24 13:56
Not sure if this is the right thing to do but if you replace switch_core_session.c:1728 `switch_core_session_write_lock(session);` with the following (taken from switch_core_session.c:1163) this fixes the problem.
```
	/* Acquire a read lock on the session or forget it the channel is dead */
	if (switch_core_session_read_lock(session) == SWITCH_STATUS_SUCCESS) {
		switch_core_session_write_lock(session);
	}
```

**Comment by remdragon** [comment] 2021-02-24 23:29
@shaunjstokes if you look at the related tickets posted above, you'll see a similar suggestion is rejected by the devs because it would cause memory corruption. The issue is that some code somewhere is not releasing a lock that it should be.

In the meantime, we seem to have eliminated the problem by changing bridge_early_media from true to false. We went from hundreds of zombies a day to having gone several days now without a single zombie.

**Comment by shaunjstokes** [comment] 2021-02-25 08:32
@remdragon changing bridge_early_media from true to false also fixes the problem for us but this isn't a solution as we need to use bridge_early_media.

I've compared the logs with and with-out bridge_early_media and noticed that `switch_ivr_bridge.c:731` and `switch_ivr_bridge.c:1944` are missing for the loopback b leg when using bridge_early_media.

When using bridge_early_media the loopback b leg is answered on `switch_ivr_originate.c:3798` instead of `switch_ivr_bridge.c:731`, and the hangup is on `mod_loopback.c:584` instead of `switch_ivr_bridge.c:1944`.

I suspect the problem which results in the lock not being released is somewhere in these subtle differences.

**Comment by shaunjstokes** [comment] 2021-02-25 12:31
I think I've narrowed it down to this:
```
	if (oglobals.bridge_early_media > -1) {
		switch_threadattr_t *thd_attr = NULL;
		switch_threadattr_create(&thd_attr, switch_core_session_get_pool(session));
		switch_threadattr_stacksize_set(thd_attr, SWITCH_THREAD_STACKSIZE);
		early_state.oglobals = &oglobals;
		//early_state.originate_status = oglobals.originate_status;
		early_state.ready = 1;
		early_state.ringback = &ringback;
		early_state.ttl = and_argc;
		switch_mutex_init(&early_state.mutex, SWITCH_MUTEX_NESTED, switch_core_session_get_pool(session));
		switch_buffer_create_dynamic(&early_state.buffer, 1024, 1024, 0);
		switch_thread_create(&oglobals.ethread, thd_attr, early_thread_run, &early_state, switch_core_session_get_pool(session));
	}
```

Looks like there's been some changes in v1.10.3 which affect the above, rolling back to v1.10.2 isn't an option as this results in errors while compiling.

It's possible the bug was triggered in this commit but requires further testing to confirm:
https://github.com/signalwire/freeswitch/commit/bfd02beef8f231e42117206437280ceb3478e4f8

**Comment by shaunjstokes** [comment] 2021-02-25 13:05
I can confirm it was caused by commit https://github.com/signalwire/freeswitch/commit/bfd02beef8f231e42117206437280ceb3478e4f8

Here's the fix:
```
	for (i = 0; i < MAX_PEERS && i < state->ttl; i++) {
		switch_core_session_t *session = state->oglobals->originate_status[i].peer_session;
		switch_channel_t *channel = NULL;

		if (session) channel = switch_core_session_get_channel(session);

		if (!session || !channel || !switch_channel_up(channel)) {
			continue;
		}

		if (switch_core_session_read_lock(session) == SWITCH_STATUS_SUCCESS) {
			state->oglobals->originate_status[i].peer_session = session;
			state->oglobals->originate_status[i].peer_channel = channel;
		}
	}
```

**Comment by fetristan** [comment] 2021-04-16 10:39
Same problem with 1.10.5 / 1.10.3 / 1.10.2 .
A call B
B call C
B transfer A on C and sometimes we will have a blocked line.

We have an hangup on the call of B and C but not a unbridge, he will come only when the call between A and C will be hangup.

A and C have a normal call BUT B and C always have a line into show calls and A leg is not killable (no session exist), we have to kill B leg, this kill the blocked line BUT the call of A and C too.

Can we have a fix or do we have to go back into the 1.8 version ?
I saw this script : https://github.com/ccppprogrammer/clean_fs_calls.sh but i think it's not a normal solution.
I tried to use the patch of shaunjstokes but we had other problem (some CLI were not good after transfer sometimes).

**Comment by andywolk** [comment] 2021-08-06 14:33
Should be fixed now. See https://github.com/signalwire/freeswitch/pull/1256

**Closed by andywolk** 2021-08-06 14:33 UTC
Labels: bug

**Comment by kavvalos** [comment] 2022-07-25 10:40
Hey...

I tried all solutions about this issue! 

When Leg A hung up  leg B stay active.

When Leg B hung up then all is fine ...BYE arrives to Leg A

There is any solution that some one has been tried????

**Comment by muriloventuroso** [comment] 2022-08-09 14:11
I have the same problem in  1.10.8-dev

**Comment by thanawatwat** [comment] 2023-12-01 06:52
> Here's the fix, switch_ivr_originate.c lines 1846 to 1860:
> 
> ```
> 	for (i = 0; i < MAX_PEERS && i < state->ttl; i++) {
> 		switch_core_session_t *session = state->oglobals->originate_status[i].peer_session;
> 		switch_channel_t *channel = NULL;
> 
> 		if (session) channel = switch_core_session_get_channel(session);
> 
> 		if (!session || !channel || !switch_channel_up(channel)) {
> 			continue;
> 		}
> 
> 		if (switch_core_session_read_lock(session) == SWITCH_STATUS_SUCCESS) {
> 			state->oglobals->originate_status[i].peer_session = session;
> 			state->oglobals->originate_status[i].peer_channel = channel;
> 		}
> 	}
> ```



> Here's the fix, switch_ivr_originate.c lines 1846 to 1860:
> 
> ```
> 	for (i = 0; i < MAX_PEERS && i < state->ttl; i++) {
> 		switch_core_session_t *session = state->oglobals->originate_status[i].peer_session;
> 		switch_channel_t *channel = NULL;
> 
> 		if (session) channel = switch_core_session_get_channel(session);
> 
> 		if (!session || !channel || !switch_channel_up(channel)) {
> 			continue;
> 		}
> 
> 		if (switch_core_session_read_lock(session) == SWITCH_STATUS_SUCCESS) {
> 			state->oglobals->originate_status[i].peer_session = session;
> 			state->oglobals->originate_status[i].peer_channel = channel;
> 		}
> 	}
> ```

When I install successfully (my PBX is 'FusionPBX'), I can't find 'switch_ivr_bridge.c' as you recommended. Could you please provide an alternative recommendation?

**Comment by zenichev** [comment] 2024-03-07 11:21
Same issue on the `1.10.9`.
After emulating a crash of the freeswitch with `fsctl crash` and then manually recovering sessions with `fsctl recover`, hang up works on from one side of the call (caller), if the called side sends the BYE, freeswitch terminates both legs, but for some reason doesn't send the BYE to the caller. See:

```
2024-03-07 10:55:14.532181 32.47% [DEBUG] mod_sofia.c:468 Channel [sofia/internal/1003@192.168.0.141](mailto:sofia/internal/1003@192.168.0.141) hanging up, cause: NORMAL_CLEARING
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_ivr_bridge.c:1470 ([sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141)) State Change CS_HIBERNATE -> CS_EXECUTE
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:59 [sofia/internal/1003@192.168.0.141](mailto:sofia/internal/1003@192.168.0.141) Standard HANGUP, cause: NORMAL_CLEARING
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:581 ([sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141)) Running State Change CS_EXECUTE (Cur 2 Tot 2)
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:647 ([sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141)) State EXECUTE
2024-03-07 10:55:14.532181 32.47% [DEBUG] mod_sofia.c:213 [sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141) SOFIA EXECUTE
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:323 [sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141) Standard EXECUTE
2024-03-07 10:55:14.532181 32.47% [NOTICE] switch_core_state_machine.c:341 Hangup [sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141) [CS_EXECUTE] [NORMAL_CLEARING]
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:647 ([sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141)) State EXECUTE going to sleep
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:581 ([sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141)) Running State Change CS_HANGUP (Cur 2 Tot 2)
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:337 [sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141) skip receive message [VIDEO_SYNC] (channel is hungup already)
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:338 [sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141) skip receive message [REQUEST_IMAGE_MEDIA] (channel is hungup already)
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:844 ([sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141)) Callstate Change ACTIVE -> HANGUP
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:846 ([sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141)) State HANGUP
2024-03-07 10:55:14.532181 32.47% [DEBUG] mod_sofia.c:462 [sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141) Overriding SIP cause 480 with 200 from the other leg
2024-03-07 10:55:14.532181 32.47% [DEBUG] mod_sofia.c:468 Channel [sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141) hanging up, cause: NORMAL_CLEARING
2024-03-07 10:55:14.532181 32.47% [DEBUG] mod_sofia.c:522 Sending BYE to [sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141)
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:59 [sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141) Standard HANGUP, cause: NORMAL_CLEARING
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:846 ([sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141)) State HANGUP going to sleep
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:616 ([sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141)) State Change CS_HANGUP -> CS_REPORTING
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:581 ([sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141)) Running State Change CS_REPORTING (Cur 2 Tot 2)
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:932 ([sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141)) State REPORTING
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:846 ([sofia/internal/1003@192.168.0.141](mailto:sofia/internal/1003@192.168.0.141)) State HANGUP going to sleep
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:616 ([sofia/internal/1003@192.168.0.141](mailto:sofia/internal/1003@192.168.0.141)) State Change CS_HANGUP -> CS_REPORTING
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:581 ([sofia/internal/1003@192.168.0.141](mailto:sofia/internal/1003@192.168.0.141)) Running State Change CS_REPORTING (Cur 2 Tot 2)
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:932 ([sofia/internal/1003@192.168.0.141](mailto:sofia/internal/1003@192.168.0.141)) State REPORTING
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:168 [sofia/internal/1003@192.168.0.141](mailto:sofia/internal/1003@192.168.0.141) Standard REPORTING, cause: NORMAL_CLEARING
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:932 ([sofia/internal/1003@192.168.0.141](mailto:sofia/internal/1003@192.168.0.141)) State REPORTING going to sleep
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:607 ([sofia/internal/1003@192.168.0.141](mailto:sofia/internal/1003@192.168.0.141)) State Change CS_REPORTING -> CS_DESTROY
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_session.c:1743 Session 2 ([sofia/internal/1003@192.168.0.141](mailto:sofia/internal/1003@192.168.0.141)) Locked, Waiting on external entities
2024-03-07 10:55:14.532181 32.47% [NOTICE] switch_core_session.c:1761 Session 2 ([sofia/internal/1003@192.168.0.141](mailto:sofia/internal/1003@192.168.0.141)) Ended
2024-03-07 10:55:14.532181 32.47% [NOTICE] switch_core_session.c:1765 Close Channel [sofia/internal/1003@192.168.0.141](mailto:sofia/internal/1003@192.168.0.141) [CS_DESTROY]
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:735 ([sofia/internal/1003@192.168.0.141](mailto:sofia/internal/1003@192.168.0.141)) Running State Change CS_DESTROY (Cur 1 Tot 2)
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:745 ([sofia/internal/1003@192.168.0.141](mailto:sofia/internal/1003@192.168.0.141)) State DESTROY
2024-03-07 10:55:14.532181 32.47% [DEBUG] mod_sofia.c:379 [sofia/internal/1003@192.168.0.141](mailto:sofia/internal/1003@192.168.0.141) SOFIA DESTROY
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:175 [sofia/internal/1003@192.168.0.141](mailto:sofia/internal/1003@192.168.0.141) Standard DESTROY
2024-03-07 10:55:14.532181 32.47% [DEBUG] switch_core_state_machine.c:745 ([sofia/internal/1003@192.168.0.141](mailto:sofia/internal/1003@192.168.0.141)) State DESTROY going to sleep
2024-03-07 10:55:14.552812 32.47% [DEBUG] switch_core_state_machine.c:168 [sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141) Standard REPORTING, cause: NORMAL_CLEARING
2024-03-07 10:55:14.552812 32.47% [DEBUG] switch_core_state_machine.c:932 ([sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141)) State REPORTING going to sleep
2024-03-07 10:55:14.552812 32.47% [DEBUG] switch_core_state_machine.c:607 ([sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141)) State Change CS_REPORTING -> CS_DESTROY
2024-03-07 10:55:14.552812 32.47% [DEBUG] switch_core_session.c:1743 Session 1 ([sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141)) Locked, Waiting on external entities
2024-03-07 10:55:14.552812 32.47% [NOTICE] switch_core_session.c:1761 Session 1 ([sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141)) Ended
2024-03-07 10:55:14.552812 32.47% [NOTICE] switch_core_session.c:1765 Close Channel [sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141) [CS_DESTROY]
2024-03-07 10:55:14.552812 32.47% [DEBUG] switch_core_state_machine.c:735 ([sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141)) Running State Change CS_DESTROY (Cur 0 Tot 2)
2024-03-07 10:55:14.552812 32.47% [DEBUG] switch_core_state_machine.c:745 ([sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141)) State DESTROY
2024-03-07 10:55:14.552812 32.47% [DEBUG] mod_sofia.c:379 [sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141) SOFIA DESTROY
2024-03-07 10:55:14.552812 32.47% [DEBUG] switch_core_state_machine.c:175 [sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141) Standard DESTROY
2024-03-07 10:55:14.552812 32.47% [DEBUG] switch_core_state_machine.c:745 ([sofia/internal/testuser1001@192.168.0.141](mailto:sofia/internal/testuser1001@192.168.0.141)) State DESTROY going to sleep
```

It seems to be related to the fact the caller's channel gets stuck in the following state:
```
State DESTROY going to sleep
```

Anyone else faced similar?

**Comment by zenichev** [comment] 2024-03-07 12:06
@kavvalos I tried on internal SIP profile, but that doesn't change anything.
So it seems, it has nothing to do with it.

Even though I wouldn't recommend you to use such an option in production setups, because it brings a risk to be frauded.

**Comment by kavvalos** [comment] 2024-03-08 10:01
I have try this only to outbound profile.  When I was doing outbound calls then Leg B was not possible to get BYE.  Based on the packets, When leg A sending BYE was getting Forbidden

**Comment by phamhieptel4vn** [comment] 2024-04-04 04:54
> Not sure if this is the right thing to do but if you replace switch_core_session.c:1728 `switch_core_session_write_lock(session);` with the following (taken from switch_core_session.c:1163) this fixes the problem.
> 
> ```
> 	/* Acquire a read lock on the session or forget it the channel is dead */
> 	if (switch_core_session_read_lock(session) == SWITCH_STATUS_SUCCESS) {
> 		switch_core_session_write_lock(session);
> 	}
> ```

I have the same problem in Freeswitch 1.10.10-release & FusionPBX 4.4 on Debian 10. Although the actual call has ended, the channel inside Freeswitch has not been hung up, so the CDR has not been updated.
![channel](https://github.com/signalwire/freeswitch/assets/83744201/fac83523-0435-45c1-8f06-f0c415ae22f4)
