### ISSUE TITLE
Freeswitch cannot be installed in CentOS

### ISSUE THREAD

**Issue by lawlint312** [signalwire/freeswitch#1839] opened 2022-10-25 10:31 UTC
According to this article: https://freeswitch.org/confluence/display/FREESWITCH/CentOS +7 + and + RHEL + 7, 
freeswitch still cannot be installed and crashes in this place: 
Yum install - y freeswitch config vanilla freeswitch Lang - * freeswitch sounds - *. 
What is the reason for this?
![image](https://user-images.githubusercontent.com/15106061/197750868-40f5474d-6902-4f93-9595-1104037968bc.png)

**Comment by andywolk** [comment] 2022-10-25 10:33
Have you put an actualy TOKEN value instead of `TOKEN` ?

**Comment by andywolk** [comment] 2022-10-25 10:34
https://freeswitch.org/confluence/display/FREESWITCH/HOWTO+Create+a+SignalWire+Personal+Access+Token

**Comment by andywolk** [comment] 2022-10-25 10:37
According to your screenshot you don't have access to the server. Please create a SignalWire access token. Closing this issue as not a bug.

**Closed by andywolk** 2022-10-25 10:37 UTC
Labels: bug

**Comment by lawlint312** [comment] 2022-10-25 10:39
thank andywolk!!
