### ISSUE TITLE
Wrong/continuous RTP timestamp when media playback resumes on 1.10.1

### ISSUE THREAD

**Issue by nttranbao** [signalwire/freeswitch#146] opened 2019-11-27 13:02 UTC
Hi there,

I am using  uuid_broadcast to inject a dialplan application (detect_audio) for a short period of time, to a currently playback() call. During this period, the audio playback is suspended as expected. After detect_audio() finishes its work, FS returns to playback() to resume.

With v1.10.1, upon playback() resume, RTP timestamp (called X) is continuous to the last value right before uuid_broadcast kicks in. 
This works flawlessly on v1.6.20 where RTP timestamp X is generated with a corresponding gap, and with Marker bit set.

v.1.6.10: Sample FS 1.6.20 voice&dtmf OK.RTP timestamp OK 20191127.pcapng
Ref. wall time 0: Packet #825: Seq=55849, Time=21120
Wall time +0.24s: Packet #877: Seq=55850, Time=23040, Mark

v1.10.1:Sample FS 1.10.1 voice&dtmf FAILED.RTP timestamp WRONG 20191127.pcapng
Ref. wall time 0: Packet #829: Seq=54081, Time=16160
wall time +0.24s: (Packet #881): Seq=54082, Time=16320

Is there any setting to make this work on 1.10.1, or this is a potential new bug?

Thanks and best regards,
Bao

**Comment by nttranbao** [comment] 2019-11-27 13:03
Wireshark stream analysis screenshots attached

![Stream Analysis - Sample FS 1 6 20 voice dtmf OK RTP timestamp OK 20191127](https://user-images.githubusercontent.com/1849550/69725478-48ec6680-10ec-11ea-8e6a-dfd3795d23dc.PNG)
![Stream Analysis - Sample FS 1 6 20 voice dtmf FAILED RTP timestamp WRONG 20191127](https://user-images.githubusercontent.com/1849550/69725515-5d306380-10ec-11ea-8b23-6ffbf96c91dd.PNG)

**Comment by nttranbao** [comment] 2019-11-27 13:07
Traces attached
[RTP Timestamps traces.zip](https://github.com/signalwire/freeswitch/files/3896936/RTP.Timestamps.traces.zip)

**Comment by nttranbao** [comment] 2019-11-27 13:13
![Stream Analysis - Sample FS 1 10 1 voice dtmf FAILED RTP timestamp WRONG 20191127](https://user-images.githubusercontent.com/1849550/69726101-c5cc1000-10ed-11ea-94d0-a9bdea0cefb1.PNG)

**Comment by nttranbao** [comment] 2019-11-27 14:41
` <context name="play noise">
      <extension name="play background noise">
         <condition>
            
            <action application="answer"/>
            
            <action application="playback" data="silence_stream://-1,100"/>
            <action application="hangup"/>
         </condition>
      </extension>
   </context>`

and in the ESL:
`uuid_broadcast <uuid> detect_audio::'30 5 900'`

**Comment by htrendev** [comment] 2019-12-16 15:31
I believe I experience the same timestamp problem, even though I don't use uuid_broadcast.

I see it with v1.10.1 as well and I simply playback two wav files one after the other from the dialplan. In a network trace I can see that there is an interval of 120-140ms, when FreeSWTICH sends no RTP. This brief delay doesn't bother me and it happens exactly when the first file finishes playing and before the second one starts. However, when the RTP packets start flowing again after this brief pause, they continuing from the next RTP sequence number (which is ok), but also from the next timestamp, as if there was no 120-140ms gap from the last sent packet.

I can also confirm that 1.6.19 behaves differently and that it sets the RTP timestamp correctly to accommodate for the 120-140ms lack of RTP packets.

1.10.1 (just to illustrate the problem, not an actual network capture, assume G711 and 20ms ptime)
```
RTP packet 1,   seq=1, time=0
RTP packet 2,   seq=2, time=160

--- 120ms of no RTP ---

RTP packet 3,   seq=3, time=320 (timestamp is seemingly wrong)
RTP packet 4,   seq=4, time=480
```

with 1.6.19 I'd see instead
```
RTP packet 1,   seq=1, time=0
RTP packet 2,   seq=2, time=160

--- 120ms of no RTP packets ---

RTP packet 3,   seq=3, time=1120
RTP packet 4,   seq=4, time=1280
```

At least in my case, when I use the new 1.10.1 version it results in the second file not being played back by a snom 720 phone.

**Comment by nttranbao** [comment] 2019-12-16 16:19
I also got the same issue with simple playback. htrendev can you try using application pause for like a second, as per the below link, this command should consume all pending RTPs, if any... It didn't work for me though, so for now I have to revert back to 1.6.20..

https://freeswitch.org/confluence/display/FREESWITCH/mod_dptools%3A+sleep

**Comment by htrendev** [comment] 2019-12-16 19:54
The way I understand it, sleep is meant to consume RTP from the receive queues. I actually use this  trick generously in my configuration, but in my case FreeSWITCH is just playing an IVR announcement, so it is sending audio, not receiving it. In fact I use a phrase macro and playAndGetDigits (from Python) to playback the files, but I don't think this makes any difference.

I've also tried setting `send_silence_when_idle`, but this caused different problems (it's worth a dedicated ticket).

I'll try to check if the vanilla configuration has this problem too. At least it will be easy for anyone to test against a well known configuration.

**Comment by htrendev** [comment] 2019-12-16 21:40
I was able to reproduce this easily by installing `freeswitch-meta-all` on a fresh Debian 9 server. I simply had to register some phone using the pre-configured extension 1000 and then to call from it 1001. This connected the call to voicemail, which played back several prompts. Between each prompt there was a 120-140ms gap in the RTP stream, but the timestamp in the next RTP packet didn't account for this.

It's easy to identify the packets with the problematic timestamps in Wireshark under "RTP -> Stream Analysis". Look for big jumps in the "Skew" column. Normally it should stay in the sigle digits range.

**Comment by htrendev** [comment] 2019-12-18 19:50
I've found that commit 9e3da93 introduced this problem between v1.8.0 and v1.8.1. More specifically it is the following line
```
if (!ts) ts = rtp_session->last_write_ts + rtp_session->samples_per_interval;
```

I'm not sure if it was intended like this of if it is needed at all, because in the case where the timestamp (`ts`) is 0 it will be set correctly shortly after this in the `get_next_write_ts()` function. 

IMHO the line above results in the continuous timestamps, which you and I see, because it bases the next timestamp only on the last timestamp, but otherwise ignores the elapsed time. By setting `ts` to a non zero value it unfortunately also prevents the `get_next_write_ts()` function to set the correct timestamp.

I simply removed the line above and rebuilt v1.10.1 and my problem was solved. I'm not sure if it can safely be removed without breaking the fix for [FS-11230](https://freeswitch.org/jira/browse/FS-11230) or if it simply needs to stay out of the way when files are being played back (and how).

**Comment by dragos-oancea** [comment] 2019-12-18 20:23
that is fixed in this one: https://github.com/signalwire/freeswitch/pull/182/files

**Comment by nttranbao** [comment] 2019-12-18 20:34
I confirmed that by commenting out the line "if (!ts) ...", the RTP timestamp behavior in 1.10.1 looks good and matches what is in 1.6.20...

Thanks a lot for pointing this out.

Regards,
Bao

> I've found that commit [9e3da93] introduced this problem between v1.8.0 and v1.8.1. More specifically it is the following line

> ```
> if (!ts) ts = rtp_session->last_write_ts + rtp_session->samples_per_interval;
> ```

**Closed** 2020-01-28 20:10 UTC
